### PR TITLE
--push flag for stack image container

### PR DESCRIPTION
**Pull request by snoyberg**
@dysinger can you look this one over?

### CODE REVIEW

**Comment by fizruk** [comment]
I am not sure it actually makes sense to have Docker commands replicated in Stack.
While `stack image container` is useful to build an image without having to specify custom `Dockerfile` (thus removing reasonable amount of boilerplate), managing Docker images is not Stack's job.
That is, I don't think Stack should `push`/`run`/`exec`/etc.
It won't remove any boilerplate and we can name the image in `stack.yaml` to then use `docker` to do something to it.

**Comment by snoyberg** [comment]
I'm thinking about the case of automated tooling (like Travis CI, for instance) where you don't want to have to hard-code the name of the Docker tag in two places.

**Comment by fizruk** [comment]
@snoyberg well, you obviously know better if it makes sense to have this in Stack :) nonetheless...

It would be somewhat convenient feature for a simple CI scenario.
But in some more complicated scenarios I would like also (from the top of my head) to automatically tag images (e.g. with Git tags), run and test container based on this image. Would these features also fit into `stack image container`? Or should they be left for `docker`?

**Comment by snoyberg** [comment]
I'm not certain. I wasn't even certain of this PR, which is why it's a PR :)

I think the tagging would make sense, but I'd probably draw the line at
running/testing containers. That's just an arbitrary line in the sand that
makes sense to me though.

On Fri, Sep 25, 2015 at 11:54 AM, Nickolay Kudasov <notifications@github.com

**Comment by dysinger** [comment]
@snoyberg I'm neutral if it should be in or out of stack.  I buy the argument that it's a simple command contained in a tool that's already installed. 

The P/R looks fine. You would need to have a very specific remote-friendly 'name' setting in stack.yaml for it to work.  Might want to error if there's no 'name' setting in stack.yaml because docker will just error underneath if you are trying to push "cool-app"

eg, the project dir might be "cool-app" but docker push of an image called "cool-app" would just error.  You would be required to have a name like "https://docker-registry.my.domain/myuser/myimage" for the push to "just work."

**Comment by snoyberg** [comment]
Maybe we just need a `stack image container-name` command or something like that, which will print the image name to stdout. Then scripts could look like:

```
stack image container
$NAME=$(stack image container-name)
docker push $NAME
docker tag $NAME $NAME-$GITREV
```

And so on.

**Comment by fizruk** [comment]
As an alternative `stack image container` might receive `name` through a command line argument like this:

```
$ stack image container --name $NAME
```

Then we just have to set `NAME` variable and use it for both `stack` and `docker`:

```
stack image container --name $NAME
docker push $NAME
docker tag $NAME $NAME-$GITREV
```

I think I would prefer this to special `container-name` command.

**Comment by fizruk** [comment]
I have just thought that maybe a command printing an option from `stack.yaml` might be useful.
But instead of an arbitrary command for specific option (like `container-name`) we might introduce a command to get any (or almost any) option. It then can be used to get container name like this:

```
$ stack option image.container.name
```

I am however not sure what else people might use such `stack option` for.

**Comment by fizruk** [comment]
I believe my `stack option` suggestion connects to `stack config` in #115.

**Comment by snoyberg** [comment]
Taking the option on the command line defeats the idea of a general purpose tool that would be able to build/push any user's repository.

While in theory having `stack option` may be sufficient, it wouldn't work well for cases when Stack is figuring out the image name itself.

**Comment by dysinger** [comment]
@snoyberg I didn't mean to kill the P/R.  I get the need for this.  CI needs to build with stack & then if it finishes, it needs to know the name of the image to push to a remote repo.  The name can be derived or over-ridden in the stack.yaml.  The CI kinda needs to know what's happened in order to do anything with `docker push`.  So we either need to provide output that's grok-able from the `image container` command or else be able to list the image names that it would produce.

**Comment by snoyberg** [comment]
I closed because I think outputting the name would be a better approach

**Pull request closed without merging**
