### PR TITLE
Compile custom Setup.hs instead of interpreting them (fixes #1041)

### LINKED ISSUE #1041: Stack is extremely slow for Cabal, due to custom setup script
Stack uses runghc to run custom Setup scripts, which for Cabal means that builds are unusably slow as all of Cabal is interpreted. In these cases, I just stop having Cabal bootstrap itself because Stack is so slow in this case. I don't know, can Stack maybe build the script or something?

### PR DESCRIPTION
**Pull request by snoyberg**
Pinging @mgsloan for review. I just (ab)used your existing code for GHCJS, please sanity check that I didn't do anything terrible.

Also pinging @ezyang, who's probably interested in this.

### CODE REVIEW

**Comment by mgsloan** [comment]
LGTM!  Such a concise change :D

**Comment by snoyberg** [comment]
Fortunately someone did all the hard work for me already

**Comment by ezyang** [comment]
Heh. Back in Cabal land, we actually just axed the custom Setup.hs because it was more headache than it was worth. But this looks reasonable. (Question: when does Setup get rebuilt in this setup?)

**Comment by snoyberg** [comment]
We ask GHC to build each run, and trust it to be smart enough to not
recompile unnecessarily

**Comment by ezyang** [comment]
(This actually would work pretty poorly for old-bootstrapped Cabal; you'd end up rebuilding the setup script every time you make a Cabal change, but once again, we don't really care anymore!)

**Pull request merged**
