### PR TITLE
Sigmundv add redhatenterpriseworkstation support

### PR DESCRIPTION
**Pull request by sigmundv**
I have added 'redhatenterpriseworkstation' as an option in the do_distro function in the get-stack.sh script. This is a trivial change that allows the script to run on this platform.

### CODE REVIEW

**Comment by mattaudesse** [comment]
Sweet, thanks @sigmundv.

The only thing is we might be better off targeting `stable` rather than `master` (see [here](https://github.com/commercialhaskell/stack/pull/4352#issuecomment-429128795) for why). Mind toggling the destination branch, please?

**Comment by dbaynard** [comment]
@sigmundv Please rebase your branch on to `stable`, too!

**Comment by mattaudesse** [comment]
@sigmundv just in case it wasn't clear (my bad if so) we're looking for the same one line `git diff` you originally submitted but targeting `stable` rather than `master`.

You may find it easier to start fresh and branch directly from `stable`, add the `redhatenterpriseworkstation` bit again and submit that as a new PR, or you can update your current feature branch as @dbaynard suggested. We'll be all set so long as we're not including the extra commits from `master` (since those are generally pushed through to `stable` more selectively by the core developers during releases).

Thanks again!

**Comment by mattaudesse** [comment]
Closing since progress has stalled out.

If anyone would like to pick this back up please refer to [this note](https://github.com/commercialhaskell/stack/pull/5106#issuecomment-562660431).

**Pull request closed without merging**
