### PR TITLE
Add "lib" as an available comptype

### PR DESCRIPTION
**Pull request by tfausak**

### CODE REVIEW

**Comment by tfausak** [comment]
Wait... I'm not sure this does what I think it does. My goal is to build only the library -- not any executables. Is this the right way to do that?

**Comment by mgsloan** [comment]
@tfausak Unfortunately, it doesn't quite work - see https://github.com/commercialhaskell/stack/issues/3653

Makes sense to document `pkg:lib` here, but note that there is no `pkg:lib:something-else`

**Comment by tfausak** [comment]
Ah, gotcha.

Will `pkg:lib:blah` work with Cabal 2's multiple libraries per package idea?

**Comment by mgsloan** [comment]
Perhaps so!  I don't think that's plumbed through stack quite yet

**Comment by lwm** [comment]
I think this all boils down to https://github.com/haskell/cabal/issues/2780!? Nice maze there ... not sure I made it out the right way. If that is the blocking issue, should we close here and move over to a ticket to track when this will be possible?

**Comment by mgsloan** [comment]
Tracked by https://github.com/commercialhaskell/stack/issues/3486 .  It sounds like some form of per component build is possible with Cabal 2.0, but how to do that and how it will affect efficiency is unclear.

**Pull request closed without merging**
