### PR TITLE
Allow setting the docker image name, fixes #621

### LINKED ISSUE #621: Set image name for containers
I'd like to be able to set the name that stacks gives to the docker images when using `stack image container`. At the moment it just guesses them from the directory.

### PR DESCRIPTION
**Pull request by cocreature**
Because just complaining is a bit lame, I took a shot at this feature. Feel free to yell at me and tell me why this is a bad idea or what needs to be changed.

### CODE REVIEW

**Comment by snoyberg** [comment]
@dysinger Can you review this?

@cocreature Looks like this PR no longer merges with master, would you be able to update it?

**Comment by cocreature** [comment]
@snoyberg Sorry I didn't see that it broke. Rebased and force pushed.

**Comment by dysinger** [comment]
We probably want to factor in the image name here too https://github.com/cocreature/stack/blob/6784b04b2501f49ac209a4468bae85efb547c7ad/src/Stack/Image.hs#L184 where we extend the image to include specific executable entrypoints.

**Comment by cocreature** [comment]
Good catch, I changed that as well. I'll be away the next few days so sorry if I don't reply.

**Pull request merged**
