### PR TITLE
3824 Replaced throwString with fail

### PR DESCRIPTION
**Pull request by tjlaxs**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [ ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [ ] The documentation has been updated, if necessary.

Quick test described in #3824

### CODE REVIEW

**Comment by snoyberg** [comment]
Sorry, I must have misunderstood the original discussion. Moving to `fail` isn't a good idea, since (1) it's not really any better than `throwString` and (2) with GHC 8.8 it's not compatible with `RIO`. I would be in favor of moving towards concrete exception types.

**Comment by tjlaxs** [comment]
I would be willing to try to fix this, but might need a bit of more information what you mean by "concrete exception types". With `RIO` I guess something like on the "Exceptions" section on rio packages documentation would still be relevant? Looking at the code base this pattern seems to show up in multiple places.

**Comment by snoyberg** [comment]
Yes, that's the basic idea. Want to push a commit making a change in one or two locations and I can review if it's in the right direction?

**Comment by snoyberg** [comment]
No update here, I'm going to close for now. If you're interested in pursuing, please reopen.

**Pull request closed without merging**
