### PR TITLE
GUIDE: document --compile and --optimize

### PR DESCRIPTION
**Pull request by simonmichael**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [ ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by simonmichael** [comment]
Ping

**Comment by mattaudesse** [comment]
Thanks for this @simonmichael.

Did you target `master` instead of `stable` on purpose? Normally documentation updates are supposed to target the latter.

**Comment by simonmichael** [comment]
No @mattaudesse, I didn't know about stable.

**Comment by simonmichael** [comment]
And I know, it says it right there of course. Too much boilerplate for my small brain, sorry!

**Comment by mattaudesse** [comment]
@simonmichael happens to the best of us haha.

I'm happy to merge this if you want to reset the target.

**Comment by simonmichael** [comment]
@mattaudesse, I've ended up creating #5426. Thanks.

**Pull request closed without merging**
