### PR TITLE
[WIP] Add feature to configure build plan download URL.

### PR DESCRIPTION
**Pull request by igrep**
Fixes https://github.com/commercialhaskell/stack/issues/1794

# Left TODOs

- [ ] Test (Really necessary?)
- [ ] Rename/Restructure the new configuration item if you can find better ones.
    - It may not have to be split into `lts` and `nightly`.
- [ ] Documentation (I want to write after you approve).
- [ ] ChangeLog.

Feel free to advice me on the source code structure, the new configuration item, and any others!

### CODE REVIEW

**Comment by mgsloan** [comment]
Since we may want to configure quite a few different URLs, why not just call this `StackURLs`?  The fields can specify that they are prefixes.  This would correspond to the configuration file option

```
urls:
    lts-prefix: ...
    nightly-prefix: ...
    ...
```

Also, I don't see actual usage of this, just types and commandline parsing.

**Comment by igrep** [comment]
> Since we may want to configure quite a few different URLs, why not just call this `StackURL`s?

You

> Also, I don't see actual usage of this in the diff, just types and commandline parsing.

OMG! :scream: Seems I've deleted the change by mistake! Sorry, fix soon.

**Comment by igrep** [comment]
> Since we may want to configure quite a few different URLs, why not just call this `StackURL`s?

You mean I should unify the configurations like `download-prefix` in `package-indices` and `latest-snapshot-url` into `StackURL`?
Sounds good, but I have to consider `stack.yaml`'s compatibility doing that.
Can I make a separate pull request to make a new configuration item to unify them?
I guess the change would be very big.

> Also, I don't see actual usage of this in the diff, just types and commandline parsing.

OMG! :scream: Seems I've deleted the change by mistake! Sorry, fix soon.

**Comment by igrep** [comment]
Fixed and rebased!

**Comment by mgsloan** [comment]
We can just deprecate the `latest-snapshot-url` field and add it to this urls list.  I think the indices urls can be left where they are

**Comment by mgsloan** [comment]
Oops sorry for letting this languish.  LGTM, thanks a bunch!

**Comment by TerrorJack** [comment]
Thank you for this awesome work!

**Comment by igrep** [comment]
Oh my... :astonished: I was actually in progress.
I was planning to push https://github.com/commercialhaskell/stack/commit/5874b9ee660e6ff997e4a1b78522fb56376b5dc4 ...
But, Okay! Thanks!

**Comment by mgsloan** [comment]
Oh, sorry, I was in PR cleanup mode

**Pull request merged**
