### PR TITLE
Remove the `--os` flag.

### LINKED ISSUE #2227: Remove the "--os" flag
I was investigating how to build for production (I'm on a Mac, I want to build for Linux), and noticed that there's a flag:

```
stack - The Haskell Tool Stack

Available options:
  --os OS                  Operating system, e.g. linux, windows
```

I cannot find any documentation on this. If it's available I'd appreciate a nudge in the right direction, but otherwise, some documentation for the flag would be appreciated.

I understood the flag as being the target OS for builds, but when passing "--os linux" in a build on a Mac, I get a Mach-O binary, not a linux compatible binary.

### PR DESCRIPTION
**Pull request by 0xmohit**
Fixes #2227

### CODE REVIEW

**Comment by sjakobi** [comment]
Thanks for working on this!

Can you add an entry to the changelog and check if there's any documentation that needs to be changed or removed?

**Comment by 0xmohit** [comment]
Added a ChangeLog entry (wasn't familiar with it's existence).  Will look into the docs to determine if anything else needs to change.

**Comment by sjakobi** [comment]
No worries about the AppVeyor failure BTW, that's caused by https://github.com/commercialhaskell/stack/pull/2457.

**Comment by 0xmohit** [comment]
Unable to find any reference to `--os` in the [docs](https://docs.haskellstack.org), so I suspect there's nothing else to change here.

**Pull request merged**
