### PR TITLE
Don't add blank lines back into multiline strings.

### PR DESCRIPTION
**Pull request by philderbeast**
Fix for #5861.

### CODE REVIEW

**Comment by mpilgrem** [comment]
@philderbeast, thanks. However, I have identified a test case where the fix does not work as intended (where the original includes a [block indentation indicator](http://yaml-multiline.info/)):

~~~yaml
resolver: lts-19.23
packages:
- .
user-message: |2
    This is line one.

    This is line two.

    This is line three.
~~~

becomes:
~~~yaml
resolver: lts-19.23
packages:
- .
user-message: |2
    This is line one.



    This is line two.

    This is line three.
install-ghc: true
~~~

As indicated by the link above, multi-line strings in YAML can take a number of forms.

**Comment by philderbeast** [comment]
> As indicated by the link above, multi-line strings in YAML can take a number of forms.

Interesting. I did test for that but encountered:

```
> stack run stack -- config set system-ghc true
Could not parse '/Users/pdejoux/dev/src/cabalism/stack-5600/stack.yaml':
YAML parse exception at line 29, column 4,
while parsing a block mapping:
did not find expected key
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

Trouble is I'd run my test for a nested multi-line string, not one for a value of a top-level key.

```yaml
nested:
  user-message: |2
    If building Stack on macOS, you are advised to use stack-macos.yaml as the
    project-level configuration file, and command:

    stack --stack-yaml stack-macos.yaml build

    See that configuration file for further information.
```

I'd assumed that if these don't parse then I didn't need to cover those cases. I'll try again.

**Comment by philderbeast** [comment]
@mpilgrem could you take another look please? The last commit gets around the indentation indicator.

**Comment by mpilgrem** [comment]
@philderbeast, thanks again. I am, however, having trouble with this example:

~~~yaml
resolver: lts-19.23
packages:
- .

user-message: >2

  This is line one.

  This is line two.

  This is line three.
install-ghc: false
~~~

becomes:

~~~yaml
resolver: lts-19.23
packages:
- .

user-message: |2



  This is line one.

  This is line two.
  This is line three.
install-ghc: true
~~~

**Comment by mpilgrem** [comment]
I don't want to discourage you in solving your 'complex' approach, but I think the 'simple' alternative set out below 'just works'.

I view the problem as '(if needed) replace one line in a YAML file', not 're-create an ordered YAML file from a YAML object created from a YAML file'.

This also preserves the number of spaces between the key and its value, when switching the value.

Extracts only:

~~~haskell
    -- We don't need to worry about checking for a valid yaml here
    rawConfig <- liftIO (readFileUtf8 (toFilePath configFilePath))
    config <- either throwM return (Yaml.decodeEither' $ encodeUtf8 rawConfig)
    newValue <- cfgCmdSetValue (parent configFilePath) cmd
    let cmdKey = cfgCmdSetOptionName cmd
        cmdKey' = Key.fromText cmdKey     -- Text
        newValue' = decodeUtf8With lenientDecode $ Yaml.encode newValue  -- Text
        file = toFilePath configFilePath  -- String
        file' = T.pack file               -- Text
        file'' = fromString file          -- DisplayBuilder
    newRawConfig <- case KeyMap.lookup cmdKey' config of
        Nothing -> do
            logInfo $ file'' <> " has been extended."
            pure $ rawConfig <> cmdKey <> ": " <> newValue'
        Just oldValue -> if oldValue == newValue
            then do
                logInfo $ file'' <> " already contained the intended \
                    \configuration and remains unchanged."
                pure rawConfig
            else do
                logInfo $ file'' <> " has been updated."
                switchLine file' cmdKey (T.stripEnd newValue') []
                    (T.lines rawConfig)
    liftIO $ writeFileUtf8 file newRawConfig
  where
    switchLine file cmdKey _ _ [] = error $ "The impossible happened: " <>
        T.unpack cmdKey <> " not found in YAML file " <> T.unpack file <> "."
    switchLine file cmdKey newValue searched (oldLine:rest) =
        let cmdKeyPlain = cmdKey <> ": "
            cmdKeySingleQuote = "'" <> cmdKey <> "': "
            cmdKeyDoubleQuote = "\"" <> cmdKey <> "\": "
            -- This, below, assumes that a top-level key will not be indented in
            -- the YAML file. It recognises key:, 'key': or "key":.
            mSuffix =   T.stripPrefix cmdKeyPlain oldLine
                    <|> T.stripPrefix cmdKeySingleQuote oldLine
                    <|> T.stripPrefix cmdKeyDoubleQuote oldLine
        in  case mSuffix of
                Just suffix -> do
                    let (spaces, suffix') = T.span (== ' ') suffix
                        comment = T.dropWhile (/= ' ') suffix' -- Maybe ""
                        newLine = cmdKeyPlain <> spaces <> newValue <> comment
                    pure $ T.unlines (reverse searched <> (newLine:rest))
                Nothing ->
                    switchLine file cmdKey newValue (oldLine:searched) rest
~~~

**Comment by mpilgrem** [comment]
@philderbeast, I am hoping to release Stack 2.9.1 this weekend. I don't know what your own timing is, but my 'Plan B' (if necessary) is to include the simple approach above in Stack 2.9.1 as an interim measure.

**Comment by mpilgrem** [comment]
I have merged #5867 as an interim measure - my 'Plan B'.

**Comment by philderbeast** [comment]
I was away for a long weekend. I want to add testing and spin off the `YamlUpdate` module into its own package. I think this is useful outside of stack.

**Comment by mpilgrem** [comment]
I am going to close this draft pull request, as I understand that it was overtaken by events.

**Pull request closed without merging**
