### PR TITLE
Fix permission error when haddock files are copied within stack --nix

### PR DESCRIPTION
**Pull request by YPares**
In order to fix https://github.com/commercialhaskell/stack/issues/1832 , as @mrkkrp suggested we switch to `path-io-1.1.0`
Can people test it to be sure no other permission problems appear?

### CODE REVIEW

**Comment by YPares** [comment]
@aspiwack Could you try this one?

**Comment by aspiwack** [comment]
@YPares this solved it for me, indeed.

**Comment by YPares** [comment]
@mrkkrp https://travis-ci.org/commercialhaskell/stack/jobs/115291952
I suppose this failure with 7.8.4 is normal since `path-io-1.1.0` doesn't exist in the resolvers that contain GHC 7.8.4.
Does someone know the resolver used for this test?

**Comment by mrkkrp** [comment]
You need to edit `stack-7.8.yaml` file as well.

**Comment by YPares** [comment]
Arf, yes, sorry indeed.

2016-03-11 16:53 GMT+01:00 Mark Karpov <notifications@github.com>:

**Comment by mgsloan** [comment]
LGTM, thanks!

**Pull request merged**
