### PR TITLE
Add Dev Container Configuration Files

### PR DESCRIPTION
**Pull request by benz0li**
* [x] Any changes that could be relevant to users have been recorded in ChangeLog.md.
* [x] The documentation has been updated, if necessary

No updates to ChangeLog.md and documentation required.

### CODE REVIEW

**Comment by benz0li** [comment]
I tried to be *minimally invasive*, i.e.

* Did not touch the `LICENCE` of Stack (the software)
    * Created a separate `LICENCE` file in the `.devcontainer` folder  
        ℹ️ Mentioning that `The code in this directory is not part of Stack (the software) and,`...

I hope this is fine and the instructions in the additional `README.md` in the `.devcontainer` folder are sufficient.

@mpilgrem What do you think? Any objections? Or additions?

**Comment by benz0li** [comment]
See https://github.com/jgm/pandoc/pull/9039#issuecomment-1699041653 ff for the discussion about adding Dev Containers to the Pandoc repository.

**Comment by benz0li** [comment]
The Haskell extension errors in the default Dev Container configuration: `Failed to find the GHC version of this Cabal project. Error when calling cabal exec -v0 -- ghc --print-libdir`.

```bash
cabal exec -v0 -- ghc --print-libdir
```

```
Error: cabal: Could not resolve dependencies:
[__0] trying: stack-2.12.0 (user goal)
[__1] trying: pantry-0.9.2 (dependency of stack)
[__2] trying: digest-0.0.1.7 (dependency of pantry)
[__3] rejecting: digest:+pkg-config (conflict: pkg-config package zlib-any,
not found in the pkg-config database)
[__3] rejecting: digest:-pkg-config (manual flag can only be changed
explicitly)
[__3] fail (backjumping, conflict set: digest, digest:pkg-config)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: digest, stack, digest:pkg-config,
pantry
Try running with --minimize-conflict-set to improve the error message.
```

---

Quick fix: Set constraint `digest ==0.0.1.3` in `cabal.config`.  
❓ Proper fix?

**Comment by benz0li** [comment]
Test online with GitHub Codespaces at https://github.com/benz0li/commercialhaskell-stack/tree/add-dev-containers

See also https://docs.github.com/en/codespaces/developing-in-codespaces/creating-a-codespace-for-a-repository#creating-a-codespace-for-a-repository

**Comment by mpilgrem** [comment]
@benz0li, I understand that GitHub Codespaces is a cloud-based x86_64-based Linux-based development environment service that GitHub users can pay for, and a repository (like Stack's) can assist those Codespaces users by providing a configuration (usually located in a `.devcontainer` directory) that encourages consistency of development experience. That is, essentially, where my own understanding ends.

So, some questions:
* is there a good reason to have a different *form* of licence (MIT v BSD 3-Clause) for the `.devcontainer` configuration?
* are there any particularly 'opinionated' aspects to this configuration that are worthy of identification/discussion here? (Nothing against opinions, as such - I would just like to understand what might be 'debatable'.)

Finally, when this is settled, it would be good to add something (some pointer to the specific `README`) to (a) `CONTRIBUTING.md` and (b) the `*.md` files in `docs\maintainers`.

**Comment by mpilgrem** [comment]
@benz0li, I did not follow your `cabal.config` comment/question. I think Stack's `cabal.config` is currently up to date.

**Comment by benz0li** [comment]
> @benz0li, I did not follow your `cabal.config` comment/question. I think Stack's `cabal.config` is currently up to date.

Please open in Codespaces or VS Code (using https://github.com/benz0li/commercialhaskell-stack/tree/add-dev-containers) with the default Dev Container configuration; wait until all VS Code extensions are installed; open file `src/Stack.hs`.  
👉 See the error message from the VS Code [Haskell extension](https://marketplace.visualstudio.com/items?itemName=haskell.haskell) as mentioned in https://github.com/commercialhaskell/stack/pull/6228#issuecomment-1706612226.

Should one be able to create Stack with Cabal (the tool) as well?  
ℹ️ If not, this error message is probably a result of this fact.

> EDIT: Often, when there are `digest` problems, it seems to be because the tool `pkg-config` is missing from the environment.

That is not the case. See https://github.com/commercialhaskell/stack/pull/6212#issuecomment-1684499748 ff.

**Comment by benz0li** [comment]
> @benz0li, I understand that GitHub Codespaces is a cloud-based x86_64-based Linux-based development environment service that GitHub users can pay for, and a repository (like Stack's) can assist those Codespaces users by providing a configuration (usually located in a `.devcontainer` directory) that encourages consistency of development experience. That is, essentially, where my own understanding ends.

These Dev Container configuration can also be run locally/'remotely (SSH)' with VS Code using Docker/Podman on both `Linux/x86_64` and `Linux/AArch64`.  
ℹ️ I run it on my MacBook Pro M2 (`arm64` aka `AArch64`) using Docker Desktop.

Dev Containers end "it works on my computer"-debates quickly because there is a Dev Container config to reproduce the issue.

**Comment by benz0li** [comment]
> * is there a good reason to have a different _form_ of licence (MIT v BSD 3-Clause) for the `.devcontainer` configuration?

No. The MIT license is just my preferred OSS licence.

I could also use the BSD 3-Clause with `.devcontainer/scripts/fix-chsh.sh` as an exception, or not providing a `LICENSE` file at all.
In case of the latter, you must mention copyright and license statement of `.devcontainer/scripts/fix-chsh.sh` in Stacks license.
ℹ️ That is the reason I chose to provide a separate license.

> * are there any particularly 'opinionated' aspects to this configuration that are worthy of identification/discussion here? (Nothing against opinions, as such - I would just like to understand what might be 'debatable'.)

These Dev Containers are based on the same docker images that 'are used'/'are going to be used' to build the amd64 and arm64 binary releases of stack.  
👉 Because the Dev Containers and the build process use the same image(s), troubleshooting is much easier if something goes wrong.

Debatable is the fact, that an *unofficial* build of GHC is used in these images. This was already discussed in https://github.com/commercialhaskell/stack/issues/6142.

> Finally, when this is settled, it would be good to add something (some pointer to the specific `README`) to (a) `CONTRIBUTING.md` and (b) the `*.md` files in `docs\maintainers`.

Agreed.

**Comment by benz0li** [comment]
> ### Tips
> 
> It has been suggested that a project must have been successfully built before the VS code extension (and HLS) is first activated on the project, for HLS to work reliably.

– [Stack and Visual Studio Code - The Haskell Tool Stack: Haskell Language Server > Tips](https://docs.haskellstack.org/en/stable/Stack_and_VS_Code/#tips)

This is exactly what [at least newer versions of] HLS try to do in the background – and fail.

I have successfully built stack (using stack); HLS still fails with the same error message.

**Comment by mpilgrem** [comment]
@benz0li, on building Stack (`lib:stack`, `exe:stack` - I have not yet tried other components its Cabal file) with Cabal (the tool), I have no problem locally with the following in the root directory of the Stack project (in the `master` branch) on Windows 11:
~~~text
> cabal --version
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library
> cabal update
...
> cabal build --with-compiler C:\Users\mike\AppData\Local\Programs\stack\x86_64-windows\ghc-9.4.6\bin\ghc.exe
...
~~~

**Comment by benz0li** [comment]
Well, well, well...

* https://github.com/haskell/cabal/issues/8923
    * https://github.com/pkgconf/pkgconf/issues/295
* https://github.com/pkgconf/pkgconf/issues/304
    https://github.com/pkgconf/pkgconf/issues/310

Fixed for default config (and only the default config) by downgrading `pkg-config` from 1.9.x to 1.8.y.

---

HLS still does not work, though:

```
Failed to run ["cabal","v2-repl","lib:stack"] in directory "/workspaces/stack". Consult the logs for full command and error.
Failed command: cabal --builddir=/home/vscode/.cache/hie-bios/dist-stack-7d4030fb4073a5f963b4594938e6876d v2-repl --with-compiler /home/vscode/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/vscode/.cache/hie-bios/ghc-pkg-2e9e7382b10dc1de912243f849341f70 lib:stack
Build profile: -w ghc-9.4.6 -O1
In order, the following will be built (use -v for more details):
 - stack-2.12.0 (first run)
Preprocessing library for stack-2.12.0..

Error: setup: can't find source for Build_stack in src, src/unix/,
/home/vscode/.cache/hie-bios/dist-stack-7d4030fb4073a5f963b4594938e6876d/build/aarch64-linux/ghc-9.4.6/stack-2.12.0/build/autogen,
/home/vscode/.cache/hie-bios/dist-stack-7d4030fb4073a5f963b4594938e6876d/build/aarch64-linux/ghc-9.4.6/stack-2.12.0/build/global-autogen

Error: cabal: repl failed for stack-2.12.0.



Process Environment:
HIE_BIOS_GHC: /usr/local/lib/ghc-9.4.6/bin/ghc-9.4.6
HIE_BIOS_GHC_ARGS: -B/usr/local/lib/ghc-9.4.6/lib
```

**Comment by mpilgrem** [comment]
`Build_stack` is a module that is auto-generated by Cabal - see `stack.cabal` and the (`custom-setup`) `Setup.hs` (function `generateBuildModule`). So, HLS will not find its source code in Stack's repository. The module is only compiled when Cabal flag `hide-dependency-versions` is False (False by default; True when a release version of Stack is built).

**Comment by benz0li** [comment]
> So, HLS will not find its source code in Stack's repository.

Is there a way to tell HLS to ignore this module? With a '[cradle](https://docs.haskellstack.org/en/stable/Stack_and_VS_Code/#cradle)' - an [hie.yaml file](https://hackage.haskell.org/package/hie-bios#stack) - in the project's root directory?

@mpilgrem Thank you for all the feedback. Highly appreciated.

**Comment by benz0li** [comment]
Until further notice, the Haskell Language Server and the VS Code Haskell extension is not installed (= disabled) in all Dev Container configurations. Due to https://github.com/commercialhaskell/stack/issues/6154.

With the ['Default' configuration](https://github.com/benz0li/commercialhaskell-stack/blob/add-dev-containers/.devcontainer/devcontainer.json), Haskell now builds using both Stack and Cabal.

**Comment by mpilgrem** [comment]
@benz0li, on a cradle for HLS, I've not commited one to the repository because I think it forces a choice of either Stack or Cabal (the tool). That seemed to me to be inappropriate to impose, even for Stack's own repository.

**Comment by benz0li** [comment]
Fixed in the `glcr.b-data.ch/ghc/ghc-musl` images themselves: https://github.com/benz0li/ghc-musl/commit/c492963e50504a203ee547d2e621940b8da85f9b

**Comment by mpilgrem** [comment]
@benz0li, for your information, in the `master` branch, I have reorganised directories in Stack's repository (#6231) but that should not affect your pull request, which does not touch those directories.

**Comment by mpilgrem** [comment]
@benz0li, for your information, I have added some information about how to use HLS with the Stack project here: https://docs.haskellstack.org/en/latest/CONTRIBUTING/#haskell-language-server.

**Comment by benz0li** [comment]
> @benz0li, for your information, I have added some information about how to use HLS with the Stack project here: https://docs.haskellstack.org/en/latest/CONTRIBUTING/#haskell-language-server.

Haskell extension + HLS work fine with the proposed cradle for Stack. I have updated the instructions accordingly:  
https://github.com/benz0li/commercialhaskell-stack/tree/add-dev-containers/.devcontainer#haskell-language-server-hls

I tried the following cradle for Cabal:

```yaml
cradle:
  cabal:
  - path: "./src"
    component: "lib:stack"
  - path: "./app"
    component: "exe:stack"
  - path: "./tests/integration"
    component: "exe:stack-integration-test"
  - path: "./tests/unit"
    component: "test:stack-unit-test"
```

But this still leads to the error described in https://github.com/commercialhaskell/stack/pull/6228#issuecomment-1708177302.

**Comment by mpilgrem** [comment]
@benz0li, regarding:
> But this still leads to the error described in [#6228 (comment)](https://github.com/commercialhaskell/stack/pull/6228#issuecomment-1708177302).

Somehow, after an initial `stack build`, HLS knows how to find generated module `Build_stack` (the source code is in the `build/global-autogen` directory of `stack path --dist-dir`; the build artefacts in the `build` directory) but it seems (from your experience) that there is no analogue in the case of Cabal (the tool). I do not know enough about Cabal (the tool) or HLS to know why.

**Comment by benz0li** [comment]
> I do not know enough about Cabal (the tool) or HLS to know why.

@mpilgrem No worries.

I will try a few more things. If I do not find a solution, I might ask over at https://github.com/haskell/haskell-language-server.

**Comment by mpilgrem** [comment]
@benz0li, I got HLS to work with the Stack project on Windows with Cabal, but it was 'ugly'. This is what I did:

1.  Installed Cabal 3.8.1.0 with GHCup, and ran `cabal update` (because Cabal does not do that automatically, like Stack does).
2.  Noted that HLS was treating `./Setup.hs` as if it were a Cabal script file - so added the following 'Cabal script' comment to its head, to stop HLS from complaining about a missing `{- cabal:` start:
    ~~~haskell
    {- cabal:
    build-depends:   Cabal < 3.12
                   , base >=4.14.3.0 && <5
                   , filepath
    -}
    ~~~
3.  Noted that HLS was looking somewhere in (in my case) in `--builddir=C:\Users\mpilgre\AppData\Local\hie-bios\dist-stack-31d950a719134407968bb13e4dd138b2` for `Stack_build.hs`, so ran:
    ~~~text
    stack exec --no-ghc-package-path -- cabal --builddir=C:\Users\mpilgre\AppData\Local\hie-bios\dist-stack-31d950a719134407968bb13e4dd138b2 build
    ~~~
    
    As I am a Stack user on Windows, I need `stack exec` to provide (a) GHC and (b) MSYS2 in the environment. I need to specify `--no-ghc-package-path` because Cabal objects if `GHC_PACKAGE_PATH` is set.
4.  Now HLS works with VS Code. However, I have to run VS Code in the same environment:
    ~~~text
    stack exec --no-ghc-package-path -- code .
    ~~~

**Comment by benz0li** [comment]
> Finally, when this is settled, it would be good to add something (some pointer to the specific `README`) to (a) `CONTRIBUTING.md` and (b) the `*.md` files in `docs\maintainers`.

@mpilgrem As https://github.com/commercialhaskell/stack/pull/6235 looks good I will think about the above now.

**Comment by benz0li** [comment]
Added [hlint](https://github.com/ndmitchell/hlint) and [yamllint](https://github.com/adrienverge/yamllint) to the Dev Containers and re-enabled the VS Code [Haskell extension](https://marketplace.visualstudio.com/items?itemName=haskell.haskell) by default.

After merging the latest changes from branch master, the HLS works fine in the default Dev Container.

**Comment by benz0li** [comment]
I think the current `.devcontainer/README.md` should go to `docs/maintainers/devcontainers.md`.

Then, I suggest `.devcontainer/README.md` to contain

```markdown
See [haskellstack.org > Stack's code (advanced) > Maintainers > Dev Containers](https://doc.haskellstack.org)
or [../doc/maintainers/devcontainers.md](../doc/maintainers/devcontainers.md) for
more information.
```

@mpilgrem Can you make a suggestion how and where in `CONTRIBUTING.md` to refer to `docs/maintainers/devcontainers.md`?

**Comment by mpilgrem** [comment]
@benz0li, regarding:
> Can you make a suggestion how and where in `CONTRIBUTING.md` to refer to `docs/maintainers/devcontainers.md`?

My suggestion on 'where' is to give it its own section near the end, after the section on 'Haskell Language Server'.

My suggestion on 'how', is about 'assumed knowledge' of the reader: imagine you are writing to help somebody who is about to start a course on computer science at university. Hyperlinks to where they can read more to understand the context may assist.

**Comment by benz0li** [comment]
@mpilgrem Please review.

Thank you.

**Comment by mpilgrem** [comment]
@benz0li, thanks! I'll merge. It maybe that when I see how the `*.md` render on the website that I tweak them for editorial consistency, but I can do that separately.

**Pull request merged**
