### PR TITLE
Using nix native functions to retrieve derivation output paths

### PR DESCRIPTION
**Pull request by YPares**
In response to https://github.com/commercialhaskell/stack/issues/2435

For packages with splitted outputs, this solves the need to include both `zlib.out` & `zlib.dev` or
`ncurses.out` & `ncurses.dev` in `packages:` in stack.yaml

Now, you can just put the package name in yout stack.yaml, and the right output will be found by nix.

### CODE REVIEW

**Comment by YPares** [comment]
@puffnfresh Can you try it and tell me if it works OK for you?

**Comment by YPares** [comment]
Note that it doesn't break compatibility: stack.yaml explicitely mentionning [zlib.out, zlib.dev] for instance will continue to work. This will just pass nonexisting directories to --extra-lib-dirs (as it already did).

**Comment by mgsloan** [comment]
@YPares LGTM, but I haven't tried it.  Feel free to merge if it works

**Comment by YPares** [comment]
@mgsloan Ok! I'm just awaiting for @puffnfresh input.

**Comment by puffnfresh** [comment]
@YPares I'll give it a go tomorrow morning.

**Comment by puffnfresh** [comment]
Before:

```
$ stack --nix repl
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Using main module: 1. Package `hello-example' component exe:hello-example-exe with main-is file: /home/brian/code/stack-hello-example/app/Main.hs
Configuring GHCi with the following packages: hello-example
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
<command line>: can't load .so/.DLL for: libz.so (libz.so: cannot open shared object file: No such file or directory)
```

After:

```
$ stack --nix repl
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Using main module: 1. Package `hello-example' component exe:hello-example-exe with main-is file: /home/brian/code/stack-hello-example/app/Main.hs
Configuring GHCi with the following packages: hello-example
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Lib              ( /home/brian/code/stack-hello-example/src/Lib.hs, interpreted )
Ok, modules loaded: Lib.
[2 of 2] Compiling Main             ( /home/brian/code/stack-hello-example/app/Main.hs, interpreted )
Ok, modules loaded: Lib, Main.
*Main Lib> 
```

So :+1:  :fireworks:

**Pull request merged**
