### PR TITLE
Added workaround explaination for non-English, Windows users of GHCJS (#1448)

### PR DESCRIPTION
**Pull request by Lewerow**
A brief instruction about the locale problem - since it hits a small group of users (non-en), it's quite hard to track it alone.

### CODE REVIEW

**Comment by tolysz** [comment]
Could you make this pull request to `stable` branch?

**Comment by tolysz** [comment]
Unfortunately, I do not have enough GitHub-fu to rebase just  this one commit to `stable`.

**Comment by mgsloan** [comment]
@tolysz Here's how I do it, with the [hub tool](https://github.com/github/hub):

```
mgsloan@computer:~/fpco/stack$ git checkout https://github.com/commercialhaskell/stack/pull/2630
Updating Lewerow
remote: Counting objects: 4, done.
remote: Total 4 (delta 3), reused 3 (delta 3), pack-reused 1
Unpacking objects: 100% (4/4), done.
From git://github.com/Lewerow/stack
 * [new branch]      master     -> Lewerow/master
M	doc/yaml_configuration.md
M	src/Stack/Build/ConstructPlan.hs
Branch Lewerow-master set up to track remote branch master from Lewerow.
Switched to a new branch 'Lewerow-master'

mgsloan@computer:~/fpco/stack$ git checkout stable
Switched to branch 'stable'
Your branch is behind 'origin/stable' by 367 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

mgsloan@computer:~/fpco/stack$ git reset --hard origin/stable
HEAD is now at 85031ed Update ghcjs.md

mgsloan@computer:~/fpco/stack$ git cherry-pick Lewerow-master 
error: could not apply 788b28a... Added workaround explaination for non-English, Windows users of GHCJS (#1448)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
```

I then used magit (emacs) to resolve the conflicts and push the changes: https://github.com/commercialhaskell/stack/commit/2d1850e3fba8b60c7a6715be584471a63d0629f0

**Comment by Lewerow** [comment]
thanks! I didn't manage to get to the computer yesterday to change target

**Comment by mgsloan** [comment]
No worries, @Lewerow !

**Pull request closed without merging**
