### PR TITLE
Comp/package component refactoring

### PR DESCRIPTION
**Pull request by theobat**
So this a work in progress, I'm stuck because I don't know how to get the proper set of components a local package should build (current behavior is, I try to ubild every component, which probably cause some of the errors in the tests).

@qrilka this is the PR I mentioned earlier.

Maybe you can review this (once the other doc PR is merged) and give me some feedback (it's still very messy)

### CODE REVIEW

**Comment by qrilka** [comment]
@theobat the diff seems to contain #5464 - would you mind rebasing?

**Comment by theobat** [comment]
yeah sorry I already did it

**Comment by qrilka** [comment]
Not sure about internal libraries and getting installed components info is one of questions that need to be resolved if we keep the way Stack currently works.

As for components - by default all of them should be included but filtered out by build flags which set whether tests/benches are to be included.

Hope this helps at least a bit.

I'll start reviewing this tomorrow

**Comment by qrilka** [comment]
@theobat I had some (not very thorough) overview of this PR and I'm not sure what kind of a feedback do you want. In the code I don't see any obvious problems (but I had rather high-level overview of the diff) and tests are surely failing as GitHub shows. Maybe you have some concrete questions I could help finding an answer for? Do you have a plan how to continue here? If I was attacking this I would start with some MVP, e.g. doing a very minimal example with only `base` as a dependency but also involving components and then increase number of features used as you progress.

**Comment by qrilka** [comment]
@theobat are you still working on this?

**Comment by theobat** [comment]
@qrilka I'll admit I don't have a lot of time, I wish I did, so I guess my answer is "not right now, and probably not enough in the coming weeks/months". The other significant issue is stack does not build on my mac anymore which does hinder the whole process (I also have ubuntu but it's not my day to day work computer so it's less convenient).
Finally I don't know what's wrong with my changes, I only added a component name to the build proceses, so I'll have to look at the tests one by one to see what's wrong. I suspect it's related to inconsistent flags between component based builds and tests but it's hand wavy...

**Comment by qrilka** [comment]
It looks like I have also not that much time, I thought about trying out your branch but didn't find time yet. As about mac - that's surely not something I could help with. If you have any ideas about immediate tasks here I could look into - please share, probably that could make it more easy to find some time if it were something more concrete.

**Comment by theobat** [comment]
So, I managed to fix the issue with cocoa on mac thanks to this : https://github.com/purescript/purescript/issues/3960#issuecomment-743069720

I'll try to look at the failing tests in the coming weeks

**Pull request closed without merging**
