### PR TITLE
Add --no-tests parameter to stack test

### PR DESCRIPTION
**Pull request by JulianBirch**
New version of the PR addressing #430. Piggybacks on the `toRun` concept introduced in the last week now. No large scale splitting out of existing code.

### CODE REVIEW

**Comment by snoyberg** [comment]
This seems fine overall, but I think the naming is confusing. Perhaps `--no-run-tests`?

**Comment by JulianBirch** [comment]
Seems sensible. Will try to update it tonight.

On Monday, July 6, 2015, Michael Snoyman <notifications@github.com> wrote:

> This seems fine overall, but I think the naming is confusing. Perhaps
> --no-run-tests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/pull/517#issuecomment-118892655>
> .
>


-- 
Sent from an iPhone, please excuse brevity and typos.

**Comment by JulianBirch** [comment]
Here's a revised (and re-rebased) version.

**Comment by snoyberg** [comment]
Thanks!

**Comment by JulianBirch** [comment]
Thanks for all your help!

On Tuesday, July 7, 2015, Michael Snoyman <notifications@github.com> wrote:

> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/pull/517#issuecomment-119042293>
> .
>


-- 
Sent from an iPhone, please excuse brevity and typos.

**Pull request merged**
