### PR TITLE
Refactorings using mapMaybeA and forMaybeA

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by mrkkrp** [comment]
Note that won't work with GHC 7.8 because applicative is not superclass of monad there. See the log.

**Comment by borsboom** [comment]
We do still need to support building Stack on GHC 7.8.

**Comment by rvion** [comment]
@borsboom Sorry in advance if this has been discussed before, but should we really support stack on GHC 7.8 ?
I ask the question because stack is not really a library one will depend on,

**Comment by sjakobi** [comment]
Thanks for the heads up regarding GHC 7.8!

I've force-pushed a fix.

**Comment by sjakobi** [comment]
Thanks for the heads up regarding GHC 7.8!

I've force-pushed a fix.

**Comment by borsboom** [comment]
Thanks!

**Pull request merged**
