### PR TITLE
Fix a case of unnecessary dependency rebuilding #3035

### PR DESCRIPTION
**Pull request by mgsloan**
See https://github.com/commercialhaskell/stack/issues/3035

I think it makes sense to include this in the release candidate, since it's the first version with custom-setup.

### CODE REVIEW

**Comment by sjakobi** [comment]
The change makes sense to me but it doesn't appear to fix original issue. Even when I delete `~/.stack/snapshots` and `stack clean --full` I still see the behavior described in #3035.

**Comment by borsboom** [comment]
Including in rc/v1.4.0 makes sense to me, so feel free to merge when ready.

**Comment by mgsloan** [comment]
@sjakobi Ah, good catch!  Issue was that this computed info gets stored in a cache.  Normally, we'd just bump the version tags.

However, when investigating this I noticed that the errors for peeking when both the tag and format have changed are rather poor.  Decode errors in the contents took priority over tag matching.  I've released store-0.4.1, which handles this.

There was also an encoding change with Map for this store release.  If we delayed on updating store version, then this would cause further cache invalidation down the road.  Best to avoid this when feasible!

@borsboom I think it's good to go, seems to work just fine.  Since I've just made this change quite a bit larger, it might be worth further review.  Feel free to merge if it looks alright

**Comment by sjakobi** [comment]
OOM while building store with GHC-7.10.3: https://travis-ci.org/commercialhaskell/stack/jobs/207616671#L327

Not sure if this needs further investigation in `store`.

Here, we should probably switch to using the [sudo-enabled Travis environment](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments) that has 7.5 GB memory instead of 4.

**Comment by sjakobi** [comment]
Looks like the other build failures were caused because they weren't aware of store-0.4.1 yet.

**Comment by sjakobi** [comment]
Works on my machine though! Nice work, @mgsloan! :+1:

**Comment by borsboom** [comment]
We should make sure the CI works before merging.

**Comment by borsboom** [comment]
@mgsloan: is the `store` upgrade actually necessary to fix the bug?  I'm hesitant to do that for v1.4.0.

**Comment by mgsloan** [comment]
@borsboom Not strictly necessary.  But if we don't do it now, then the cache for MiniBuildPlan will be invalidated for both this release and next release.  It's straightforward to do it that way instead.

**Comment by mgsloan** [comment]
I've gone with the more conservative change.  Merging!

**Comment by borsboom** [comment]
Tests passed, so I merged it.

**Pull request merged**
