### PR TITLE
Detect resolver change in `stack solver`

### LINKED ISSUE #2252: stack solver --update-config does not update the config if the resolver changes
I tried to use
```
stack solver --update-config --resolver lts-6
```
to change my `stack.yaml` from a different resolver. This works if `stack solver` has to apply other changes (`extra-deps` for example). But if the yaml requires no change but the `resolver` field, then `stack solver` says:
```
test -z "$STACK" || echo "resolver: lts-1.0" > stack.yaml # dummy value
test -z "$STACK" || stack solver --update-config --resolver "$STACK"
Selected resolver: lts-3.22
Using configuration file: stack.yaml
Using cabal packages:
- arbtt.cabal

No changes needed to stack.yaml
```

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #2252.

@harendra-kumar: Could you take a look?

### CODE REVIEW

**Comment by harendra-kumar** [comment]
Awesome! Looks good to me.

**Comment by harendra-kumar** [comment]
I renamed moldResolver to mOldResolver (94c2cb2). without camel case it sounded like `mold resolver` rather than `m old resolver`.

**Comment by sjakobi** [comment]
> I renamed moldResolver to mOldResolver (94c2cb2). without camel case it sounded like mold resolver rather than m old resolver.

Haha, yeah, that's better! :)

Thanks for the review!

**Comment by mgsloan** [comment]
I actually have used the `mold` prefix a lot, I don't mind either way, though.

**Pull request merged**
