### PR TITLE
Suppress haddock-dependent paths

### PR DESCRIPTION
**Pull request by dfithian**
https://github.com/commercialhaskell/stack/issues/4892

I did my best, let me know any feedback!

Verified by hand:

```bash
➜  stack git:(master) stack exec stack -- path --local-doc-root          
➜  stack git:(master) stack exec stack -- --haddock path --local-doc-root
/Users/dan/tvision/git/stack/.stack-work/install/x86_64-osx/95706d9a7eb5a51fa4f678a8b9b1b45f1c109a287d472625bc347d888d9a84f7/8.2.2/doc
```

@snoyberg @qrilka

### CODE REVIEW

**Comment by snoyberg** [comment]
I think this behavior could be very confusing: now `--local-doc-root` will fail to produce output without `--haddock` without any explanation for why. The original goal in the code was to rerun things with Haddock enabled for the relevant settings, but for some reason it didn't work. That IMO would be the ideal thing to fix here.

**Comment by dfithian** [comment]
Okay, I thought this was what you were asking for [here](https://github.com/commercialhaskell/stack/issues/4892#issuecomment-504713382) but I am happy to do whatever, so long as the behavior can be specified. Can you be more specific as to the behavior you want so that I can test it appropriately? In the original issue description, `stack path --local-doc-root` was not the location where haddock ended up via `stack build --haddock --no-haddock-deps`, so are you saying that you want the paths to match? Are there more test cases I should be aware of?

**Comment by snoyberg** [comment]
The problem is, when I was working on updating this specific code, I didn't really understand the `UseHaddocks` bit, or have solid test cases to work from. Which is why I ended up breaking it, and why I'm having trouble giving you clear guidance. Sorry about that.

I believe the requirements here should be one of the following:

* `stack path --local-doc-root` gives a meaningful error message, while `stack path --local-doc-root --haddock` succeeds
* `stack path --local-doc-root` gives the same output as `stack path --local-doc-root --haddock`, which is the same path specified with `stack build --haddock`

Does that make sense? I prefer the latter myself.

**Comment by qrilka** [comment]
@snoyberg I don't quite understand what this PR is trying to solve and the way it works in the version 2.1.1 is exactly what you give in your 2nd option, e.g.:
```
qrilka@qdesktop ~/ws/h/hatrace $ stack-2.1.1 path --local-doc-root
/home/qrilka/ws/h/hatrace/.stack-work/install/x86_64-linux-tinfo6/eaf56c794f2da90e300a3577de4d3f6adad92b776bfc0e13009088580835816a/8.6.3/doc
qrilka@qdesktop ~/ws/h/hatrace $ stack-2.1.1 path --local-doc-root --haddock
/home/qrilka/ws/h/hatrace/.stack-work/install/x86_64-linux-tinfo6/eaf56c794f2da90e300a3577de4d3f6adad92b776bfc0e13009088580835816a/8.6.3/doc
```

**Comment by snoyberg** [comment]
@qrilka Looks like you're right. @dfithian I was debugging too many different things at once, and started seeing things that weren't there. It looks like the original bug report had to do with `--no-haddock-deps` producing a different hash, not a lack of `--haddock` being passed to `stack path`. Despite my initial thoughts, it could be that I actually implemented `Stack.Path` correctly in the first place.

**Comment by dfithian** [comment]
Oh, I see. I agree that it is working correctly currently and I can see that additionally passing `--no-haddock-deps` changes the hash. That seems appropriate given the straightforward use case of using `--haddock`, and it is apt that you would need to specify `--no-haddock-deps` for the correct path in that case. So I will close this PR. Thank you both for your explanation and your time!

**Pull request closed without merging**
