### PR TITLE
--file-watch should respect VCS boring/ignore files

### PR DESCRIPTION
**Pull request by agrafix**
( A first attempt of Part 1 for #703 )

This is a very basic implementation and I've moved out most of the logic to a separate package ( http://hackage.haskell.org/package/ignore ) as I would like to reuse it for other projects. Don't know if this is the desired approach, looking for feedback :-)

### CODE REVIEW

**Comment by snoyberg** [comment]
Thanks!

**Comment by luigy** [comment]
One of `ignore`'s dependencies requires having `pcre` headers installed
I had to install them through my package manager first on OS X 10.10... I thought they would come with Xcode :/

**Comment by agrafix** [comment]
Yeah, to correctly interpret mercurials hgignore files you need pcre :-(

**Comment by snoyberg** [comment]
Hmm, that's actually a serious problem, since it will greatly complicate
the windows installation story. Is there any subset of functionality we can
get without the library dependency?

**Comment by agrafix** [comment]
The simplest thing would probably be to add a flag to the `ignore` package to build w/o pcre and then use that on windows. .gitignore files will still work fine as the run on globs, but .hgignore files will only work with `syntax: glob` enabled. Would that be a solution?

**Comment by snoyberg** [comment]
It's a little awkward to provide different functionality by OS. And this
may be a problem on Mac as well, I'm not sure. Purely from the ease of
install perspective, my answer would be to fully drop mercurial support,
but that's not a great answer either.

**Comment by borsboom** [comment]
It's not ideal on Linux either (I just had to install libpcre on a system for the latest version of stack).

**Comment by agrafix** [comment]
I'll add a flag to the ignore package to remove pcre support for now as a quick fix, and then we can look for a long term fix.

**Pull request merged**
