### PR TITLE
Give Setup.hs all project dependencies #897

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by snoyberg** [comment]
Two thoughts:

1. I think using `-package-id` with the `GhcPkgId` would be more resilient
2. There's some funny business around the Cabal library itself, namely: stack always builds with the global Cabal package for various reproducibility issues, whereas the snapshot may contain a different version of the Cabal library. I think- though I'm not certain- that the `deps` should exclude any `Cabal` package listed there.

Would you be able to try out these two changes and confirm that it still works for your use case?

Thanks for looking into this!

**Comment by mitchellwrosen** [comment]
Yeah. I also seem to have broken `stack sdist` :)

Am I correct in thinking that for `sdist`, it doesn't really matter if Setup.hs has access to all global, snapshot, and local packages? Or do the same reproducibility objections apply?

**Comment by snoyberg** [comment]
I think that's correct, but perhaps @mgsloan can weigh in on the requirements when running `Setup.hs` for the sdist command.

**Comment by mgsloan** [comment]
I'm not sure if the same reproducibility objections apply.  However, to me it makes sense to run Setup.hs in exactly the same way for both cases.

The current change will certainly break `sdist`, because having `deps = Set.singleton ident` means that Setup.hs depends on the package itself!  It should be possible to get dependencies for sdist as well.

**Comment by mitchellwrosen** [comment]
Yeah, I know why it's failing, @mgsloan. I'm having a second look over the code - it's not entirely clear to me how to get a list of dependencies without actually executing a build and such with all of the infrastructure in Stack.Build.Execute.hs

**Comment by snoyberg** [comment]
One thing worth considering: make a first stab that just change the behavior for `stack build`, but for `sdist` keep the old behavior, with a note that this could be improved in the future.

**Comment by mitchellwrosen** [comment]
@snoyberg Ok, updated

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
