### PR TITLE
Move toFilePathNoTrailingSlash to new module Path.Extra

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
If there is a better way to dedupe `toFilePathNoTrailingSlash` please tell me!

**Comment by sjakobi** [comment]
I've found even more duplicates of that function. 

Closing until I've fixed the others.

**Comment by borsboom** [comment]
I like `Path.Extra`.  There might be a few functions in Path.IO that are not actually I/O related that would more properly belong in this new module.

**Comment by sjakobi** [comment]
> There might be a few functions in Path.IO that are not actually I/O related that would more properly belong in this new module.

I'll have a look at those!

**Pull request closed without merging**
