### PR TITLE
make the resolver error show a hopefully more clear description for nightlies

### PR DESCRIPTION
**Pull request by radix**
This is a quick fix for #241. More could be done -- perhaps show a URL to a definitive list of possible values?

### CODE REVIEW

**Comment by bitemyapp** [comment]
@radix https://www.stackage.org/snapshots is the list

https://www.stackage.org/nighty always redirects to latest

**Comment by radix** [comment]
@bitemyapp thanks. I'll add that link. @snoyberg Do you think maybe that /snapshots page could be updated to show the slugs in addition to the pretty names, so it's easy to copy to the resolver field from the main listing?

**Comment by radix** [comment]
Okay, I added the link, but the message is getting really long. I tried to put in a line break, but I realized that the exceptions are just being shown, so the \n is being escaped in the output. Here's what the output looks like now:

```
AesonException "Invalid resolver value: lts-2.9a. Possible valid values include lts-2.12, nightly-YYYY-MM-DD, and ghc-7.10. See https://www.stackage.org/snapshots for a complete list."
```

Pretty long :)

**Comment by snoyberg** [comment]
I don't see a problem, should be an easy change to make.

**Comment by radix** [comment]
Build passed - I guess this is ready for review (I assume I should add the 'ready' label, so I'll do that, but if that's wrong let me know)

**Comment by chreekat** [comment]
I am also guessing, but I think 'ready' means 'ready to be worked on (no questions outstanding)' while the tag you are looking for is 'needs-confirmation' :)

**Comment by snoyberg** [comment]
"ready" does indeed mean "can be worked on." It's provided by waffle.io.

**Pull request merged**
