### PR TITLE
Snapshot to sourcemap

### LINKED ISSUE #4409: Replace Stack.Snapshot with code using SourceMaps
After #3922 gets merged there will be 2 different ways to deal with snapshots:

1. The old one in `Stack.Snapshot`
2. New source maps from `Stack.Types.SourceMap`

It makes sense to remove code duplication coming from this

### LINKED ISSUE #4410: Fix or remove solver command
The command `stack solver` wan't updated for quite a long time. Its functionality wasn't checked for `cabal-install` versions newer than `1.24` and issues a warning in such a case. Upcoming PR for #3922 2 breaks `stack solver` and it needs to be decided whether this command will be supported (and thus needs to be properly updated) or this feature will get removed in the new Stack version

### PR DESCRIPTION
**Pull request by qrilka**
Please include the following checklist in your PR:

* [ ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [ ] The documentation has been updated, if necessary.

2 integration tests fail. That was filed as #4669 

Fixes #4409 
Fixes #4410 

I didn't remove `solver` from documentation

### CODE REVIEW

**Comment by qrilka** [comment]
@snoyberg I guess `solver` removal should appear in the changelog at least, right?

**Comment by snoyberg** [comment]
Yes please, as a major change

**Comment by qrilka** [comment]
@snoyberg could you check my English 004e8833ceddba37d5a48763689a06b15aa77b0b ? I suppose we could merge the PR after that?

**Comment by snoyberg** [comment]
LGTM

**Pull request merged**
