### PR TITLE
Add stack-ghc-810.yaml and Github Actions job

### PR DESCRIPTION
**Pull request by borsboom**
This is the version for `stable`.

### CODE REVIEW

**Comment by borsboom** [comment]
@snoyberg The Github Actions checks for this are failing, but it's not obvious how the failures are related to the changes I made.  Have you seen errors like these before?

**Comment by borsboom** [comment]
I also told Github Actions to re-run the jobs from the previous `stable` build, which had succeeded in the past, but it [failed in the re-run with the same error](https://github.com/commercialhaskell/stack/runs/946750601?check_suite_focus=true).  It seems this is more of a general CI problem rather than a problem with this MR.

**Comment by snoyberg** [comment]
I put in a hacky workaround on master, which needs to be improved. I believe what's happening is that Git on Windows had an update which changes how symlinks are handled, and now `git status` _always_ shows changes on Windows for each symlink file. On master, I simply ignored the diffs for Windows, but that's not a great solution, since it means the `stack --version` shows a dirty tree. I think we can merge this PR as-is, and figure out a better fix later.

**Comment by borsboom** [comment]
Since we rely on the integration test job to build bindists, we'll have to fix it properly because we don't want official Windows releases to say they're dirty.

**Comment by snoyberg** [comment]
Agreed, though I'm kind of hoping that Git for Windows just fixes this regression soon and we don't have to do anything.

**Comment by borsboom** [comment]
Do you know if there's an issue filed somewhere for the Git for Windows issue?  I'd like to at least know when it's fixed so I can continue the release process then.

**Comment by snoyberg** [comment]
What I found was a reference in the [release notes](https://github.com/git-for-windows/git/releases/tag/v2.28.0-rc0.windows.1) to [issue 2653](https://github.com/git-for-windows/git/issues/2653). I'm not sure if that's authoritative, since that issue is closed.

**Comment by borsboom** [comment]
Thanks.  A comment in that issue identified an easy workaround: `git config --global core.fscache false`.  I added that in https://github.com/commercialhaskell/stack/pull/5361/commits/7b4ca5c432501ffafb1c5897921f6f8294900a4c and it seems to work.

**Comment by snoyberg** [comment]
Whoa! Good find, thank you!

**Pull request merged**
