### PR TITLE
Install GHC from file

### PR DESCRIPTION
**Pull request by cblp**
Implements #2224.

Should I write tests?

### CODE REVIEW

**Comment by mgsloan** [comment]
Thanks for working on this!

**Comment by mgsloan** [comment]
Why not allow setting `content-length` and `sha1` for local files?  This way you could potentially test the stack.yaml configuration before uploading, and not need to test downloading.

Also, other places that use `chattyDownload` could benefit from this as well.  While it's an unlikely case, you could specify your own 7zip version for example.

I guess the resolution of this would be to have `chattyDownload` and `verifiedDownload` take a `Either (Path Abs File) DownloadRequest`, and return a `Path Abs File` for the local location of the file.

**Comment by cblp** [comment]
> Why not allow setting `content-length` and `sha1` for local files? This way you could potentially test the stack.yaml configuration before uploading, and not need to test downloading.

OK, I'm removing warnings about them.

**Comment by cblp** [comment]
I didn't change chattyDownload, because downloading to specified path is strange — it is actually copying and it's always better to use file from original location on disk than copying it to another directory. Or not always?

**Comment by mgsloan** [comment]
Right, we'd want to call it something different.  I understand why you didn't make the change that way, it would be larger.

I don't think that this verification stuff should be coupled with downloading and should .  I can worry about that decoupling, though..

**Comment by mgsloan** [comment]
Merged!  Sorry for letting this languish.

**Comment by cblp** [comment]
Thanks!

**Pull request merged**
