### PR TITLE
Fix #5902 Change behaviour of `stack --no-install-ghc setup`

### LINKED ISSUE #5902: Doesn't respect --no-install-ghc
### Steps to reproduce

Select a version of GHC you *don't* have installed anywhere; I picked 8.8.2 for example.

1. `cd /tmp`
2. `stack new acme && cd acme`
3. `echo 'resolver: ghc-8.8.2' > stack.yaml`
4. `stack setup --no-install-ghc`

### Expected

Bail out with an error like so:

```
No compiler found, expected minor version match or newer with ghc-8.8.2 (x86_64-tinfo6) (based on resolver setting in /tmp/acme/stack.yaml).
To install the correct GHC into /home/ulidtko/.stack/programs/x86_64-linux/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
```

### Actual

Download & installation proceeds regardless of `--no-install-ghc` and `install-ghc: false` in `~/.stack/config.yml`:

```
 /t/acme> stack setup --no-install-ghc
Preparing to install GHC (tinfo6) to an isolated location.
This will not interfere with any system-level installation.
ghc-tinfo6-8.8.4: download has begun^C  
```
— contrary to [as documented](https://docs.haskellstack.org/en/v2.9.1/yaml_configuration/#install-ghc).

### Stack version

Tested on 5 builds:
 * 2.7.5 from Archlinux community repo
 * 2.9.1 from official releases here on github (`stack-2.9.1-linux-x86_64-bin`), on Archlinux
 * 2.7.5 from `ghcup` on Ubuntu 22.04 LTS
 * 2.9.1 from `ghcup` on Ubuntu 22.04 LTS 
 * 2.3.3 from stock apt repository on Ubuntu 22.04 LTS — `apt install -y haskell-stack`

— with exact same results.

Each respective build's `stack --version | head -n1` detailed below:

~~~text
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 (dirty) (8407 commits) x86_64
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 x86_64 hpack-0.34.4
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
2.3.3 x86_64
~~~

### PR DESCRIPTION
**Pull request by mpilgrem**
* [x] Any changes that could be relevant to users have been recorded in ChangeLog.md.
* [x] The documentation has been updated, if necessary

Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack on Windows 11.

### CODE REVIEW

**Review by ulidtko — CHANGES_REQUESTED** [review]
Tested from CI build — there's something missing with handling of the global config.

The straightforward test with explicit arg indeed works as expected:
```
 /t/acme> /tmp/stack-2.10.0-linux-x86_64-bin setup --no-install-ghc
The --no-install-ghc flag is inconsistent with 'stack setup'. No action taken.
```
So far so good.

However, `install-ghc: false` in the global `~/.stack/config.yaml` is supposedly equivalent, but doesn't work:
```
 /t/acme> grep install-ghc ~/.stack/config.yaml 
install-ghc: false
 /t/acme> /tmp/stack-2.10.0-linux-x86_64-bin setup
Preparing to install GHC (tinfo6) to an isolated location.
This will not interfere with any system-level installation.
ghc-tinfo6-8.8.4: download has begun^C
```

**Comment by mpilgrem** [comment]
@ulidtko, many thanks. My mistake was to reference the wrong configuration environment. The one of type `RIO Runner ()` was before the configuration files had been loaded. The one yielded by `withConfig` is after the loading of the files. I think the current iteration now works as intended. If you would like to test again, I would appreciate that.

**Review by ulidtko — APPROVED** [review]
LGTM! Tested, works as expected.

**Comment by mpilgrem** [comment]
@ulidtko, thanks!

**Pull request merged**
