### PR TITLE
Support for stack setup installing + booting GHCJS

### PR DESCRIPTION
**Pull request by mgsloan**
See https://github.com/commercialhaskell/stack/issues/749#issuecomment-142477335 for more info - this isn't expected to work out of the box, since ghcjs source tarballs need to be available and listed in stack-setup-2.yaml

### CODE REVIEW

**Comment by snoyberg** [comment]
:+1: LGTM. I'd like to test this before we merge to master. Can you update the stack-setup-2.yaml file and ping me when it's ready?

**Comment by mgsloan** [comment]
@snoyberg Ready! https://github.com/fpco/stackage-content/commit/9ef1c121bef987db3ff370768c52a49072eb8ca5

**Comment by snoyberg** [comment]
I can confirm that this worked to get GHCJS installed and usable. Please merge when you're ready.

**Comment by snoyberg** [comment]
Oh, forgot to mention: please add a comment to the ChangeLog about this (and yes, this counts as a major feature)

**Comment by fizruk** [comment]
@mgsloan how did you make a proper pre-release of GHCJS?

I am trying to use latest GHCJS with Stack and managed to make it work with this in my `stack.yaml`:

```yaml
resolver: ghcjs-0.2.0.20150930_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20150930_ghc-7.10.2:
        url: "https://github.com/fizruk/ghcjs/archive/v0.2.0.20150930.tar.gz"
```

But that `.tar.gz` archive is not a proper pre-release (e.g. it does not have `lib/cache/boot.tar`), so I had to tweak Stack locally to pass `--dev` flag to `ghcjs-boot`. I would love to make this a proper archive so that others might be able to use it, but can't find any documentation on how to do this.

**Comment by mgsloan** [comment]
@fizruk It depends on if you are making a pre-release for master (improved-base) or old-base.  If making one for old-base, first you must install and boot GHCJS.  Then, run `cabal sdist`.  With master, the process is easier and only `cabal sdist` is needed.

**Comment by fizruk** [comment]
@mgsloan I need `master` (improved base). So am I right that for `master` I don't need `ghcjs-boot` step? It seemed like `ghcjs-boot` did a lot of work compared to GHCJS install step.

**Comment by fizruk** [comment]
@mgsloan oh, there is non-trivial `Setup.hs` affecting `cabal sdist`. Will `stack sdist` also work?

**Comment by fizruk** [comment]
I have successfully set up latest GHCJS with Stack:

```yaml
resolver: ghcjs-0.2.0.20151001_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151001_ghc-7.10.2:
        url: "https://github.com/fizruk/ghcjs/releases/download/v0.2.0.20151001/ghcjs-0.2.0.20151001.tar.gz"
```

@mgsloan maybe it is worth to include it in [`stack-setup-2.yaml`](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml)?

**Pull request merged**
