### PR TITLE
Use YAML syntax for remote git location identification.

### PR DESCRIPTION
**Pull request by mboes**
As suggested by @greggwebs. The syntax proposed yesterday has the
advantage of concision, but using YAML syntax for the different
components adds marginal verbosity. As it is, the previous syntax made
extensibility problematic, whereas that's exactly where YAML
shines (what if we need an extra field to identify a particular git
commit?). Further, using YAML means people are free to include their own
metadata about package locations, without disturbing Stack.

Here's an example:

```
- location:
    git: https://github.com/kolmodin/binary
    commit: 8debedd3fcb6525ac0d7de2dd49217dce2abc0d9
```

Note that this patch *removes* the old syntax. The reasoning being -
custom user tooling would need to conservatively support both syntaxes
if there was a brief and a long syntax, because it can't assume that
other users utilized the easier to parse syntax.

### CODE REVIEW

**Comment by mboes** [comment]
cc @gregwebs @3noch. Followup to #199.

**Comment by snoyberg** [comment]
Properly pinging @gregwebs instead :)

**Comment by chrisdone** [comment]
Looks reasonable to me.

**Comment by snoyberg** [comment]
Me too, I agree on the reasoning as well.

**Comment by gregwebs** [comment]
Great!

**Pull request merged**
