### PR TITLE
Add additional information about ld errors

### PR DESCRIPTION
**Pull request by dkasak**

### CODE REVIEW

**Comment by mgsloan** [comment]
Thanks!  cherry-picked to the stable branch (updates the docs immediately), and merged to master.

**Comment by dkasak** [comment]
@mgsloan Ugh, I just noticed that docs.haskellstack.org doesn't render `*` as a bulleted list unlike Github's Markdown and botches it relatively badly. It seems I'm not the first one to make the mistake. If I clean up such errors in the document, would you be willing to merge?

**Comment by mgsloan** [comment]
Sure!  Use stable as the merge target

**Comment by dkasak** [comment]
Will do. I'll ping you once it's done.

**Pull request closed without merging**
