### PR TITLE
Set default FileWatch command to force a rebuild

### PR DESCRIPTION
**Pull request by tedkornish**
Just something which could be kind of nice.

### CODE REVIEW

**Comment by snoyberg** [comment]
I'm OK with this, but I think it should still let the user know about the `help` command for discoverability. (Yes, it mentions help at the beginning, but that's easy to miss/forget.) Maybe just add it to the "waiting for next build" line?

**Comment by tedkornish** [comment]
^ disregard: that's a mistake and not what you're looking for (fc2d25b).

> I think it should still let the user know about the help command for discoverability
> Maybe just add it to the "waiting for next build" line?

Could you clarify what you mean by "it"? As far as I'm aware, every instance of telling the user about the `help` command is still there.

**Comment by snoyberg** [comment]
I mean that pressing enter by itself today gives the user some guidance about what's going on. I can picture someone not understanding how to exit and just hitting enter, for example.

**Comment by snoyberg** [comment]
And you can ignore the AppVeyor build failures, I'm just getting that set up now.

**Pull request merged**
