### PR TITLE
Fix some redundant constraint warnings under GHC-8.0, fix compilation with GHC-7.8

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
There's one redundant constraint warning left that has me a bit stumped:

```
/home/simon/src/stack/src/Stack/Types/StackT.hs:219:1: warning: [-Wredundant-constraints]
    • Redundant constraint: MonadTrans t
    • In the type signature for:
           stickyLoggerFunc :: (HasSticky r, HasLogLevel r,
                                HasSupportsUnicode r, ToLogStr msg, MonadReader r (t m),
                                MonadTrans t, MonadIO (t m)) =>
                               Loc -> LogSource -> LogLevel -> msg -> t m ()
```

So far, all my attempts to fix it have introduced errors…

**Comment by sjakobi** [comment]
There's another warning from GHC-8.0's enhanced pattern exhaustiveness checker:

```
/home/simon/src/stack/src/Stack/Coverage.hs:295:56: warning: [-Wincomplete-uni-patterns]
    Pattern match(es) are non-exhaustive
    In a lambda abstraction: Patterns not matched: _
```

It refers to `readTixOrLog`:
```haskell
readTixOrLog :: (MonadLogger m, MonadIO m, MonadBaseControl IO m) => Path b File -> m (Maybe Tix)
readTixOrLog path = do
    mtix <- liftIO (readTix (toFilePath path)) `catch` \(ErrorCall err) -> do
        $logError $ "Error while reading tix: " <> T.pack err
        return Nothing
    when (isNothing mtix) $
        $logError $ "Failed to read tix file " <> T.pack (toFilePath path)
    return mtix
```

I believe that we could safely remove the `catch` clause and rely on [`readTix` doing all the `catch`ing](http://haddock.stackage.org/lts-5.17/hpc-0.6.0.2/src/Trace-Hpc-Tix.html#readTix).

**Comment by mgsloan** [comment]
Thanks a bunch!!

I actually think that warning in `readTixOrLog` is a GHC bug :( .  `ErrorCall` is a newtype so it should be perfectly valid to match on it in a lambda, no exhaustiveness issue.

**Comment by mgsloan** [comment]
The GHC issue is tracked by https://ghc.haskell.org/trac/ghc/ticket/8779

**Comment by mgsloan** [comment]
Remaining warnings fixed in https://github.com/commercialhaskell/stack/commit/cc57f97bc696e242669a7d508ab3c960f9e407a7

**Comment by sjakobi** [comment]
> The GHC issue is tracked by https://ghc.haskell.org/trac/ghc/ticket/8779

Thanks for digging that up!

> Remaining warnings fixed in cc57f97

That actually introduced another warning (`Pattern matche(s) are overlapped`) in GHC-7.8 and GHC-7.10 for which I have a fix in #2152. ;)

**Pull request merged**
