### PR TITLE
Promote packages to local database by ghc-options #849

### PR DESCRIPTION
**Pull request by snoyberg**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by snoyberg** [comment]
@mgsloan @borsboom Will you review the comments I've put in the changelog in this PR before I merge? I think this is the right call, but would appreciate a second (and third) opinion.

**Comment by borsboom** [comment]
So if I read this correctly, this doesn't implement the `local-only` option mentioned in https://github.com/commercialhaskell/stack/issues/849#issuecomment-320892095.

In a way, this seems similar to setting flags on a package, but IIRC that doesn't automatically promote a package to local (instead, it requires you to make the package an extra-dep).  I'm wondering if there's a justification for that difference in behaviour or if it's just by accident.

**Comment by snoyberg** [comment]
Just to unify the discussion from here and the issue: I _think_ we're in agreement that this is a fair first step, and are considering some additional changes. Let me document them here:

* Some way to apply flags in a stack.yaml file to all local packages. @mgsloan mentioned a `$locals` key. I like that, and would move to replace `*` with `$everything` to be more explicit (with a warning printed for the old syntax).
* A broader question about implicit snapshots. We could add them in under @mgsloan's idea of only having project packages and things depending on them end up in the local database. I'm open to revisiting that. And once that's in place, yes, it would make sense to promote all packages to a custom snapshot.

My recommendation is, in the interest of keeping the changesets manageable, we consider if this change is an improvement. If so, let's merge and open new issues for these enhancements.

**Comment by mgsloan** [comment]
@snoyberg Yep, that seems reasonable to me!

**Comment by snoyberg** [comment]
OK, two new issues opened. I'm going to merge this so I can get started on the other two.

**Pull request merged**
