### PR TITLE
Added lts-8 and ghc 8.0.2 to travis script

### PR DESCRIPTION
**Pull request by JustusAdam**
Updated the complex travis.yml.

Please review that my changes are correct. I'm not sure if the happy and alex versions also have to be updated.

I did test the stack and ghc-8.0.2 configurations in a travis.yml of mine though.

### CODE REVIEW

**Comment by snoyberg** [comment]
The master build is already using GHC 8.0.2 via LTS 8, is there something in this PR that isn't present on master?

**Comment by JustusAdam** [comment]
This is not the Travis is script that stack actually uses, it's the one linked in the docs, the one you recommend library authors to use. I just updated it. I don't think that change is on master yet.

**Comment by snoyberg** [comment]
Right you are, thank you for clarifying! I spent so much time fighting with Travis builds across projects last week that I have some tunnel vision. Thanks for the PR!

**Comment by JustusAdam** [comment]
No worries ;)

**Pull request merged**
