### PR TITLE
Bring cabal-install executable into $PATH for integration test

### PR DESCRIPTION
**Pull request by psibi**
This will fix integration tests (like `stack-init-solver`)
which depends on the cabal executable.

I tested that this PR works on a separate CI job here:
https://dev.azure.com/psibi2000/stack-issue-debug/_build/results?buildId=737

### CODE REVIEW

**Comment by qrilka** [comment]
@psibi regarding the solver command we have #4410 - it's possible that we'll just remove this command

**Comment by psibi** [comment]
@qrilka Thanks for the heads up. I think we can remove the associated tests if we agree on to remove the `solver` option. As of now, I think it should be okay to merge this PR for making the integration tests pass. What do you think ?

Also will the `stack init --solver` option be also removed as part of #4410 ?

**Comment by qrilka** [comment]
@psibi I didn't look much into `solver` yet, I think it's just incompatible with the latest Cabal versions, I plan to look into it soon and will check `stack init --solver` as well. Can't tell you more than that at the moment.

**Comment by psibi** [comment]
Merging this as the build failure seems to be a sporadic timeout issue.

**Pull request merged**
