### PR TITLE
Pass .o file paths to GHCi from c-sources (#756)

### PR DESCRIPTION
**Pull request by chrisdone**
This works with the `hoogle` codebase now.

Pinging @ndmitchell for merge.

@snoyberg want to give it a quick sanity check?

### CODE REVIEW

**Comment by ndmitchell** [comment]
One for @snoyberg or someone else to merge. While I have merge access, it's more an accident than something I should ever really use!

**Comment by ndmitchell** [comment]
Does this fix #756? I just tried after a `stack upgrade --git`, and Hoogle still fails with a `stack ghci` (after deleting the `ghci.bat` and `.ghci` files, to give it the best shot).

**Comment by chrisdone** [comment]
@ndmitchell It's supposed to work, I tested it with hoogle. Can you [lpaste](http://lpaste.net/) the `-v` output?

**Comment by ndmitchell** [comment]
Take a Hoogle repo (I have some changes, but I don't believe any are meaningful). Delete the `.ghci` and `ghci.bat` files. Windows. Output at https://gist.github.com/ndmitchell/a1cfa634c997684d3877

**Pull request merged**
