### PR TITLE
Dev Containers: Do not mount the user's home directory

### PR DESCRIPTION
**Pull request by benz0li**
- Remove section 'Persistence' in documentation

* [x] Any changes that could be relevant to users have been recorded in ChangeLog.md.
* [x] The documentation has been updated, if necessary

No updates to ChangeLog.md required.

### CODE REVIEW

**Comment by benz0li** [comment]
This is the default behaviour for Codespaces/'Dev Containers'.

**Comment by mpilgrem** [comment]
@benz0li, I have merged.

**Comment by benz0li** [comment]
No self-hosted `linux/arm64` runner available at the moment?

**Comment by mpilgrem** [comment]
Yes, not at the moment. I'm looking into to it, with others, behind the scenes - hoping to find a remedy soon.

**Pull request merged**
