### PR TITLE
Make the paths stored in precompiled-cache Stack-root relative

### PR DESCRIPTION
**Pull request by da-x**
Because these paths always point inside the Stack root, better make them relative to the Stack root, making the Stack root more easily relocatable, in the future.

This change is backward-compatible.

### CODE REVIEW

**Comment by mgsloan** [comment]
Makes sense.  Stack roots aren't going to be relocatable any time very soon though, unfortunately, cabal package build results have absolute paths.

**Comment by da-x** [comment]
Apart from this, we have the Cabal conf files that you mentioned, the GHC pkgdb, some shell wrappers and RPATH in DSOs. All of these are easier and known formats that are easy to deal with. Only the precompiled-cache is very much Stack-specific.

BTW, I'm working on a 'stack relocate' command. I'm designing it to be used under `rpmbuild` mock chroot. @juhp

**Comment by mgsloan** [comment]
That's awesome!  I'd love to be able to copy build directories for https://github.com/commercialhaskell/stack/issues/1634 , but I'm not sure how this would get around binary dependencies on the `Paths_*` module 

See these stack issues on relocatable data files:  https://github.com/commercialhaskell/stack/issues/1262 https://github.com/commercialhaskell/stack/issues/848

(compiled in absolute path dependencies on these data files is the issue)

**Comment by da-x** [comment]
There's a partial working for binaries that assumes that the path you are relocating to is shorter or of the same length, and that there are no checksums or signatures. This is mostly the case in build servers, which tend to build under paths that quite long, e.g. `/build/rpmbuild/[sometimes-long-rpm-package-name-plus-version/build-root/...`, verifiably shorter than the usual install destination `/usr`. The trick is to assume null termination of the strings, pad the right side with zero characters, and do binary replacement inside the generated files. It's a bit nasty, though.

**Comment by mgsloan** [comment]
Better hope some machine code doesn't magically resemble a filepath! :D

**Comment by da-x** [comment]
The `package.cache` file proved stubborn with the zero padding, but I've realized that for the UNIX case I can pad the beginning of the path with `/`, since `/////usr` is as valid a path as `/usr`. So now `stack relocate` works ([implementation](https://github.com/commercialhaskell/stack/commit/de66db70857161c42f498b438d048630d6072dba)).

**Pull request merged**
