### PR TITLE
Newer nightly

### PR DESCRIPTION
**Pull request by jeffhappily**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [ ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by snoyberg** [comment]
@jeffhappily can you rebase this into a single commit?

@borsboom any objection to this?

**Comment by borsboom** [comment]
It looks like this leaves us without any GHC 8.6-based snapshot, which means we can't be guaranteed that Stack will be build-able with that version.  After #5162 is merged this would be fine (since it changes `stack.yaml` to use a GHC 8.6-based snapshot), but if not a `stack-lts-14.yaml` and `snapshot-lts-14.yaml` should be added and CI configuration adjusted to also build that.

**Comment by snoyberg** [comment]
With the change to GHC version based Stack config files, this won't be necessary. I'll include a `stack-ghc-88.yaml` in the `newer-lts` branch instead.

**Comment by snoyberg** [comment]
Just realized that the code changes in here need to be included, my mistake.

**Pull request merged**
