### PR TITLE
Stop truncating all-cabal-hashes repo (#2175)

### LINKED ISSUE #2175: "Right Nothing" printed to the console during setup
with

````
>stack --version
Version 1.1.3, Git revision 8f7e62fbe3620a4b0ae5eb833cebfa50820f5050 x86_64 hpack-0.14.0
````

when i attempt a setup i see:
````
⚡ 05:37 PM noon ∈ ~>stack --resolver nightly-2016-05-13 setup
Run from outside a project, using implicit global project config
Using resolver: nightly-2016-05-13 specified on command line
Downloaded nightly-2016-05-13 build plan.    
Did not find .cabal file for servant-yaml-0.1.0.0 with Git SHA of d7c8a8eaf9e7c215433f8f39daac7fc6cf116325
Right Nothing
Did not find .cabal file for reducers-3.12.1 with Git SHA of bcebf11be1770ac480d9d0ee6238044f143a57f8
Right Nothing
Did not find .cabal file for math-functions-0.1.7.0 with Git SHA of 5870cda6259e8a838c8cb22043b9d3cbf55d9a8e
Right Nothing
Did not find .cabal file for hw-prim-0.0.0.10 with Git SHA of 3658e799df0b7fceb045899b7a3d686b960b5d01
Right Nothing
Did not find .cabal file for hspec-megaparsec-0.1.1 with Git SHA of 116c887f005a6e599dc9b6ce5627f1b69782f44b
Right Nothing
Did not find .cabal file for dixi-0.6.9.1 with Git SHA of 17cba908e23588d9e5b67541f53afd8590c5c30f
Right Nothing
Did not find .cabal file for cron-0.4.0 with Git SHA of d485877cb0e43ee1b8fcdaa0a7224acbd753186c
Right Nothing
stack will use a locally installed GHC
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
````

it's mildly unfortunate that `Right Nothing` is printed here.

introduced a few weeks ago by https://github.com/commercialhaskell/stack/commit/f483e820d23707ec4ddd3fcdf38385e36f769203#diff-2068556e565acc62de252ac25ed550c4R288

### PR DESCRIPTION
**Pull request by Blaisorblade**
Fixes #2175.
This fix is quite minimal, and it comes with a significant slowdown for the first `stack update`, which is why I used "type: discuss" for this PR.
```
$ ./.stack-work/install/x86_64-osx/lts-6.0/7.10.3/bin/stack update
remote: Counting objects: 797395, done.
remote: Compressing objects: 100% (449683/449683), done.
remote: Total 797395 (delta 337171), reused 797302 (delta 337078), pack-reused 0
Receiving objects: 100% (797395/797395), 193.46 MiB | 4.16 MiB/s, done.
Resolving deltas: 100% (337171/337171), completed with 1 local object.
```

However, local tests confirm that #2175 disappers. Note that to see the results, one needs to remove various caches and the repo:
```
rm -f ~/.stack/build-plan-cache/x86_64-linux/lts-6.0.cache
rm ~/.stack/indices/Hackage/00-index.cache
rm -rf ~/.stack/indices/Hackage/git-update
stack update
stack setup --resolver lts-6.0 -v
```

I'd hope `stack update` would be enough without `rm -rf ~/.stack/indices/Hackage/git-update`, but I'm not sure.

EDIT: The AppVeyor failures are due to #2457; but for now I'd wait for a fix and a clean AppVeyor build just to be sure.

### CODE REVIEW

**Comment by mgsloan** [comment]
> I'd hope stack update would be enough without rm -rf ~/.stack/indices/Hackage/git-update, but I'm not sure.

I don't think it'll be sufficient.  Gotta do `git fetch --unshallow` - http://stackoverflow.com/questions/6802145/convert-shallow-clone-to-full-clone

**Comment by Blaisorblade** [comment]
Thanks, didn't know that existed! Turns out I have to do --unshallow iff `.git/shallow` exists. Can do.
```
$ ls .git/
HEAD         config       description  hooks/       index        info/        logs/        objects/     packed-refs  refs/        shallow
$ git fetch --unshallow
remote: Counting objects: 54, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 54 (delta 37), reused 42 (delta 26), pack-reused 0
Unpacking objects: 100% (54/54), done.
pgiarrusso [bluevelvet: ~/AeroFS/Repos/phd-thesis: 18:31: 7 (0)]
$ git fetch --unshallow
fatal: --unshallow on a complete repository does not make sense
```

**Comment by Blaisorblade** [comment]
Testing transition locally *by hand* in parallel with CI, so don't merge yet (hence [HOLD]).

**Comment by Blaisorblade** [comment]
Local and CI testing completed, and no opposition heard, hence merging.

**Pull request merged**
