### PR TITLE
Dev Containers: Update HLS to v2.5.0.0

### PR DESCRIPTION
**Pull request by benz0li**
Please include the following checklist in your pull request:

* [x] Any changes that could be relevant to users have been recorded in ChangeLog.md.
* [x] The documentation has been updated, if necessary

No updates to ChangeLog.md and documentation required.

### CODE REVIEW

**Comment by benz0li** [comment]
@mpilgrem See https://github.com/benz0li/ghc-musl/blob/main/.devcontainer/VERSION_MATRIX.md#current about which HLS versions are available for which GHC versions.

**Comment by hasufell** [comment]
> @mpilgrem See https://github.com/benz0li/ghc-musl/blob/main/.devcontainer/VERSION_MATRIX.md#current about which HLS versions are available for which GHC versions.

The matrix doesn't show for which platforms (sometimes there are subtle differences in bindist availiability). For a precise list you can check https://github.com/haskell/ghcup-metadata/blob/95c57ba3e4603563c1e57740b4cab4b8829b376e/hls-metadata-0.0.1.json#L1435-L1512

**Comment by benz0li** [comment]
> The matrix doesn't show for which platforms (sometimes there are subtle differences in bindist availiability). For a precise list you can check https://github.com/haskell/ghcup-metadata/blob/95c57ba3e4603563c1e57740b4cab4b8829b376e/hls-metadata-0.0.1.json#L1435-L1512

@hasufell These are [custom built](https://github.com/benz0li/ghc-musl/tree/main/packages/hls) for use with [GHC musl](https://github.com/benz0li/ghc-musl) only; build on Alpine Linux for both `linux/amd64` and `linux/arm64/v8`.  
ℹ️ Stack's Dev Containers are based on GHC musl (i.e. docker image `glcr.b-data.ch/ghc/ghc-musl`).

All images are available at https://gitlab.b-data.ch/ghc/ghc-musl/container_registry

**Comment by hasufell** [comment]
Ah thanks. I thought you're using upstream bindists.

**Pull request merged**
