### PR TITLE
Add uninstall section fixes #4170

### LINKED ISSUE #4170: No uninstall instructions
### General summary/comments 
In the docs there is only an install section
The only install instructinons are:

``curl -sSL https://get.haskellstack.org/ | sh``

But there ins not information where things are saved and how to remove them.

### Steps to reproduce

For example:

1. Install
3. Try to uninstall

### PR DESCRIPTION
**Pull request by guysoft**
As requested.

### CODE REVIEW

**Comment by guysoft** [comment]
See #4171

**Comment by mihaimaruseac** [comment]
Perfect, thanks :)

One thing, the documentation changes should target the `stable` branch, not `master`.

**Comment by mihaimaruseac** [comment]
Just realized I could change the base branch here but it brings too many commits so probably needs a cherry-pick later. Will look into it later today.

**Comment by mihaimaruseac** [comment]
Closing this as it will be incorporated later into `master` before the release of a new version. Thanks for the PR to `stable`

**Pull request closed without merging**
