### PR TITLE
Add --external flag (Needed for yesod dev server)

### PR DESCRIPTION
**Pull request by psibi**
Please include the following checklist in your PR:

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

> Please also shortly describe how you tested your change. 

Tested it using the `--external` flag that has been implemented in this patch.

Fixes https://github.com/commercialhaskell/stack/issues/3147

### CODE REVIEW

**Comment by psibi** [comment]
@snoyberg Can this be reviewed and merged ?

**Comment by snoyberg** [comment]
I know I should have thought about this earlier in the discussion process, but I'm only doing so now, apologies. Two concerns:

1. I'm not a big fan of the name `--external`. What about `--file-watch-silent` or something like that?
2. Understanding the use case again, it now sounds like this is to work around a user error of typing in commands besides `build`. Is that accurate? If so, what about having `yesod devel` intercept the `stdin` and only passing on valid commands to Stack?

Apologies for not noting this at design phase, as my previous comments probably make clear, I wasn't fully grokking the problem initially.

**Comment by psibi** [comment]
> Understanding the use case again, it now sounds like this is to work around a user error of typing in commands besides build. Is that accurate? If so, what about having yesod devel intercept the stdin and only passing on valid commands to Stack?

Yeah, that's right. I think intercepting at the `yesod devel` itself is a better idea now. :) I will see if I can patch it up in the coming days (unless you want to fix this up in the current flow).

> Apologies for not noting this at design phase, as my previous comments probably make clear, I wasn't fully grokking the problem initially.

No issues!

**Comment by mgsloan** [comment]
I think it makes sense to have yesod devel do the interception, since I don't see this flag being useful for other cases.

**Pull request closed without merging**
