### PR TITLE
Don't recompile in presence of sublibraries

### LINKED ISSUE #3899: hakyll dependency on nightly is not cached
With the resolver set to `resolver: nightly-2018-03-01`, a package depending on `hakyll` always rebuilds `haddock-library`, `pandoc`, `pandoc-citeproc` and `hakyll`. This does not happen if I set the resolver to `resolver: lts-10.7`. The rebuilds cause significant slowdowns.

Both `pandoc` and `pandoc-citeproc` [seem to be `extra-deps` of hakyll](https://github.com/jaspervdj/hakyll/blob/5dc0b60e6f607fada3d72566dcd1ca4cbfe14c4d/stack.yaml). Maybe this is related?

### Steps to reproduce

1. In `stack.yaml`, set `resolver: nightly-2018-03-01`.
2. Run command `stack build`.
4. Run command `stack build` again.

`package.yaml`: 
```yaml
name: repro

dependencies:
- base >= 4.7 && < 5
- hakyll

library:
  source-dirs: src
```

### Expected

The second `stack build` should not build anything again.

### Actual

`haddock-library`, `pandoc`, `pandoc-citeproc` and `hakyll` are rebuilt.

Output of the second `stack build --verbose`: https://gist.github.com/st3ll1s/3ef40d7d3e5513a31ef031bab129deff

### Stack version

```
root@9aa4322411fe ~# stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

### Method of installation

`curl -sSL https://get.haskellstack.org/ | sh`

### PR DESCRIPTION
**Pull request by mihaimaruseac**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

------

Tested first with the `internal-libraries` package mentioned in https://github.com/commercialhaskell/stack/issues/3899#issuecomment-375935325 and made Stack not ignore the internal library in this case.

Furthermore, tested against my own `hakyll`-based repo, to reproduce #3899.

### CODE REVIEW

**Comment by lierdakil** [comment]
@mgsloan, can this be merged/released sooner rather than later? Full rebuilds on every action are a *huge* pain.

**Comment by mihaimaruseac** [comment]
If there's any need for more work on this, I'd be happy to do it.

**Comment by snoyberg** [comment]
Sorry for the delay on reviewing this. Two comments:

1. It would be ideal if you could add an integration test to ensure this works and that the bug doesn't recur in the future. (See: https://github.com/commercialhaskell/stack/tree/d0bf58a2a663bfb81e67a6af5e752387b22d4a2e/test/integration)
2. Would it be possible to do away with the usage of `fromJust`? We generally try to skip partial functions in the codebase

Thank you for this PR!

**Comment by mihaimaruseac** [comment]
Sure. I'll do both this week.

**Comment by mihaimaruseac** [comment]
And done, was easier than expected to add the test.

**Comment by borsboom** [comment]
I've cherry-picked into the `v1.7.0` branch.

**Comment by Porges** [comment]
@borsboom can we get a `1.7.0.2` build? I'm in so much pain :grin:

**Comment by borsboom** [comment]
@Porges https://github.com/commercialhaskell/stack/releases/tag/v1.7.0.3

**Comment by Porges** [comment]
@borsboom Thanks! 🙂

**Pull request merged**
