### PR TITLE
Add an easy-to-read message showing where exes were installed

### PR DESCRIPTION
**Pull request by radix**
This is meant to address #312.

I decided that instead of *replacing* the "Copying ... to ..." output, I'd just add a new message at the end, since the "Copying" lines describe things as they're happening, and my new code just summarizes what was actually successfully installed.

The output looks like this:

```
Installed executables to /Users/radix/.local/bin/:
- stack-integration-tests
- stack
```

I'm sad to say that this is probably the most complex monadic code I've worked with, having never worked with transformer stacks at all, and being a very new Haskeller. So please give it an extra close look, though it's a very small change.

In particular I'm curious if there's an easy way for me to get a function of `[(a, b)] -> Map a [b]`. I ended up accumulating `[(a, [b])]` even though the [b] is always a singleton, and then using `fromListWith (++)` on that.

### CODE REVIEW

**Comment by chreekat** [comment]
@radix 

    > :t M.fromListWith (++) . map (fmap (:[]))
    M.fromListWith (++) . map (fmap (:[]))
      :: Ord k => [(k, a)] -> M.Map k [a]

:)

**Comment by chreekat** [comment]
I guess that's the same thing you said you did...

**Comment by radix** [comment]
@chreekat Oh, that makes sense. In some sense it's better than what I did since it lets me accumulate the list as the simpler [(a, b)] and then later turn it into a Map a [b], which is what I was looking for. OTOH the code ends up looking simpler if I just leave it the way I did it... well I'll let you or someone else decide :)

**Comment by snoyberg** [comment]
Looks good to me! I can't think of a better way to do the Map construction. Different? Sure. But not obviously better.

**Pull request merged**
