### PR TITLE
Also resolve auto-generated component files.

### PR DESCRIPTION
**Pull request by uncle-betty**
This is a proposal to address #5392.

It basically passes the Cabal version down to the place where it's needed to generate the directory paths that hold auto-generated files, `resolveComponentFiles`. These directories are then used in addition to the `hs-source-dirs` directories to find `.hs` files for a component's modules.

I'm only superficially familiar with the `stack` codebase, but it seems that at least this doesn't break any of the tests.

### CODE REVIEW

**Comment by uncle-betty** [comment]
"... didn't break any of the tests *when I ran them on my machine*" I should have said. :) I'll look into the test failures.

**Comment by uncle-betty** [comment]
Oh, never mind. The failing tests seem to be build issues caused by `casa.fpcomplete.com`.

**Review by snoyberg — APPROVED** [review]
LGTM, thanks!

**Comment by snoyberg** [comment]
Also: the server issues should hopefully be fixed. It's a temporary patch right now, but a better fix is coming. Also, we're hoping to get a new Stack release out the door. We already have the commits on `master` to make a server outage non-fatal, they just haven't been released yet.

**Comment by uncle-betty** [comment]
Great! Thanks for the review and for the merge. Current `master` now works like a charm for me.

**Pull request merged**
