### PR TITLE
Specify User-Agent on every HTTP request (#3628)

### PR DESCRIPTION
**Pull request by igrep**
Fix: https://github.com/commercialhaskell/stack/issues/3628

Wrap up functions in `Network.HTTP.Client` and `Network.HTTP.Simple` to
add User-Agent to the request object.

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

# Testing the change

I confirmed some requests are fixed by `stack setup`, `stack install`, `stack new`.
But I haven't tested all HTTP requests made by `stack`.

# For reviewers

I'm not sure especially with the name and place of the wrapper module (and the name of its functions).  
Feel free to modify for better module structure.

### CODE REVIEW

**Comment by lwm** [comment]
This looks like a solid approach to me! Perhaps, to help avoiding using the wrong function and not the wrapped one in the future, we can use a similar HLint trick like in https://github.com/commercialhaskell/stack/blob/master/.hlint.yaml#L44 - where a warning is produced (and the CI will fail) if it isn't used - assuming we always want these headers to go out? I assume so!

**Comment by igrep** [comment]
@lwm Thanks for advice!

> Perhaps, to help avoiding using the not wrapped function, we can use a similar HLint trick like in https://github.com/commercialhaskell/stack/blob/master/.hlint.yaml#L44

You mean, should I rename functions exported by `Network.HTTP.StackClient` to differ from functions in `Network.HTTP.Simple` and `Network.HTTP.Client`?
It looks like that `hlint` can suggest only when `lhs` and `rhs` are literally different as their de-qualified names.
I'm new to `.hlint.yaml`, so tell me if I get something wrong!

If I should rename, I'm going to prefix `stack` to the new functions: `stackHttpJSON`, `stackHttpLbs`, etc.

**Comment by lwm** [comment]
I'm not exactly sure either ;) I thought you could pass full import paths (like over [here](https://github.com/ndmitchell/hlint/blob/master/data/hlint.yaml#L321)) and get away with it. If you can't do that, maybe the renaming with the prefix is a better option in general - less magic!

**Comment by mgsloan** [comment]
Good stuff @igrep , thanks a bunch!

Cool idea bout using hlint to reduce likelihood of regressions, @lwm!  Indeed I'm not sure if HLint can distinguish where identifiers are imported from.  Seems like it'd be a major weakness if not, I'm guessing it can do this.  I've opened https://github.com/commercialhaskell/stack/issues/3700 to track implementing the idea.

**Pull request merged**
