### PR TITLE
Update travis instructions to use stack-0.1.5.0

### PR DESCRIPTION
**Pull request by bergmark**
I looked if there was a way to just link to the latest version, but I didn't find anything useful.

### CODE REVIEW

**Comment by borsboom** [comment]
It's possible to get the latest version's URL using an incantation like this:

    curl -sSL https://api.github.com/repos/commercialhaskell/stack/releases/latest \
        | grep '"browser_download_url": ".*/stack-[0-9\.]\+-x86_64-linux.tar.gz"' \
        | sed 's/.*"\(.*\)"$/\1/'

Not sure if you'll want to include something like this, so it might be better to just replace version numbers with `<VERSION>` and add a note to replace it with the current version, rather than needing to remember to update this document for every new version.

See are planning to include an easier "download the current version" link on the website once it's ready.  See #532.

**Comment by snoyberg** [comment]
@borsboom One concern I have is that we've had a different bindist format for the past three releases. Are we sure we're going to have something stable now? Otherwise, hard-coding a version into the document still seems prudent.

**Comment by borsboom** [comment]
@snoyberg I don't foresee changing it again anytime soon; maybe some files will be added, but there will continue to be a `stack` executable in the top-level directory of the tarball.

**Comment by phadej** [comment]
it should be:
```sh
curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xz --strip-components=1 -C ~/.local/bin
```

i.e. `--strip-components=1` for `0.1.5.0`

**Comment by borsboom** [comment]
Even better is
```
curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xz --strip-components=1 -C ~/fpco/tmp/xx stack-0.1.5.0-x86_64-linux/stack
```
(which only extracts the `stack` executable, and skips the documentation)

**Pull request merged**
