### PR TITLE
Always exact configuration

### PR DESCRIPTION
**Pull request by snoyberg**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [X] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [X] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by qrilka** [comment]
@snoyberg What is this option? I don't see it documented and I'm not sure that I understand it completely. How does it relate to bounds checking?

**Comment by snoyberg** [comment]
This flag means that we tell Cabal exactly which package identifiers should be used for each dependency, bypassing any bounds checking Cabal itself might do. The failure you noted in the previous PR was due to Cabal refusing to ignore bounds.

**Comment by qrilka** [comment]
Oh, it's from Cabal. I see now. Probably we should add a hint about it in the changelog entry?

**Comment by snoyberg** [comment]
I included a ChangeLog entry here: https://github.com/commercialhaskell/stack/pull/4678/commits/e06a3e3e3ab8a85e7660aa1a44237d2756ecb16e#diff-e705c8fadf1193ab59443a5e6c8cbe8bR79

**Comment by qrilka** [comment]
I was referring to exactly that entry, my suggestion is to mention that it's a Cabal flag

**Comment by snoyberg** [comment]
Oh, got it! Sure, I'll add that and merge to master

**Pull request merged**
