### PR TITLE
add install instructions for openSUSE Tumbleweed ,Leap and SLE12

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by mimi1vx** [comment]
https://github.com/commercialhaskell/stack/issues/1459

**Comment by borsboom** [comment]
Is there anything we'll need to do as part of the release process to ensure that new versions of Stack are available for SUSE quickly?  (duplicate from #1459, but meant to comment here)

**Comment by mimi1vx** [comment]
@borsboom we follow latest LTS in openSUSE/SLE , in devel repository in the same day as LTS minor release , in openSUSE Tumbleweed after review process so +3 days

**Comment by borsboom** [comment]
Please add a note to the SUSE instructions that make this clear, so people don't expect them to be updated immediately for a new release, and mention they're not managed by the Stack release team (similar to the note for the [Fedora Copr repo](https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md#fedora)).

Also, please add a single H2 (e.g. `## SUSE`) heading and put the different versions under it as H3 headings (e.g. `### openSUSE Tumblewead`), and add a link to it from the [README](https://github.com/mimi1vx/stack/blob/SUSE-docu/doc/README.md#how-to-install).

**Comment by borsboom** [comment]
Thanks!

**Pull request merged**
