### PR TITLE
Reduce duplication in file resolver functions

### PR DESCRIPTION
**Pull request by markus1189**
DRY up file resolver functions that only differ whether it's a file or directory by introducing internal helper functions.

### CODE REVIEW

**Comment by snoyberg** [comment]
Thanks! I'll leave to @chrisdone to review and comment on.

**Comment by markus1189** [comment]
Hope I fixed the build error due to missing `<$>` import, I just replaced it with `fmap` instead of adding CPP.

**Comment by chrisdone** [comment]
Looks good!

**Comment by markus1189** [comment]
There where still some missing Functor instances for ghc < 7.10 ...  I added them, let's see what travis says this time

**Comment by chrisdone** [comment]
I already fixed it on master, no worries.

**Comment by markus1189** [comment]
Awesome, funny how just using `liftM` in this case is better than `fmap` =)

**Pull request merged**
