### PR TITLE
Use binary-tagged, remove WithTag

### LINKED ISSUE #889: Replace Binary with something more reliable for file storage
`Binary` instances are quite problematic for file storage, since they store no metadata about the schema itself. This has led multiple times to out-of-memory issues because an `Int` was parsed as a list size, for example. We have some hacks in the code base to essentially embed magic numbers to work around this, but there are certainly better ways we can solve this with improved libraries.

A non-solution: use JSON. We tried this already, and the performance hit was significant. We need a fast (de)serialization.

### PR DESCRIPTION
**Pull request by phadej**
I tried to use the old stack and one with this patch one after each other, both pruned other's caches.

Fixes #889

### CODE REVIEW

**Comment by snoyberg** [comment]
That was a lot faster than I was expecting, thanks! This looks good to merge, just waiting for Travis. Could you also add something to the ChangeLog about this?

**Comment by phadej** [comment]
Indeed, it was quite straightforward change.

**Comment by phadej** [comment]
And for the record: `binary-tagged` will catch changes like https://github.com/commercialhaskell/stack/pull/902/files#diff-8c2944535368646d36cd90e08a658087R74 so one doesn't need to manually bump `SemanticVersion`.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
