### PR TITLE
YAML config: support Zip archives

### PR DESCRIPTION
**Pull request by da-x**
Allow to use Github's 'download as zip' in addition to Tarballs and Git clone.

### CODE REVIEW

**Comment by da-x** [comment]
Figured that the directory content handling at the end of `resolvePackageLocation` should be similar to RPTHttpZip. Would you like me to revise it?

**Comment by mgsloan** [comment]
Sure, thanks for working on this!

**Comment by da-x** [comment]
Added a second commit. I can squash and rebase if needed.

**Comment by da-x** [comment]
These travis-ci errors don't seem related, though

**Comment by sjakobi** [comment]
> These travis-ci errors don't seem related, though

I agree. I restarted the failed Travis job.

**Comment by da-x** [comment]
Looks good. Anything left to do?

**Comment by mgsloan** [comment]
After the more detailed review, it occurred to me that looking for `.zip` at the end of the URL isn't very principled.  So yup, still a bit more to do (see the inline comment)

**Comment by da-x** [comment]
Re-did the pull request in one commit.

Hopefully, decompressors don't completely blow out when received an archive of another format. At worst case we can use a file signature test library first.

Some tests show it works OK:

ZIP url:

```
2016-01-27 08:51:41.916360: [debug] Trying to untar /home/dan/dev/gh/da-x/fancydiff/.stack-work/downloaded/09b0bacd742175549a1360e5dc9fe3986826a99da98da560400c66221bc21c59.$
2016-01-27 08:51:41.916535: [debug] Got exception: Codec.Compression.Zlib: compressed data stream format error (incorrect header check) @(stack_G0jjQzQC1nCF0DYhIHVQjx:Stack$
2016-01-27 08:51:41.916604: [debug] Trying to unzip /home/dan/dev/gh/da-x/fancydiff/.stack-work/downloaded/09b0bacd742175549a1360e5dc9fe3986826a99da98da560400c66221bc21c59.$
```

Bogus URL (not an archive):

```
2016-01-27 08:52:44.697946: [debug] Got exception: Data.Binary.Get.runGet at position 4: Did not find end of central directory signature @(stack_G0jjQzQC1nCF0DYhIHVQjx:Stac$
Archive extraction failed. We support tarballs and zip, couldn't handle the following URL, http://docs.haskellstack.org/en/stable/GUIDE.html?highlight=clean downloaded to t$
````

**Comment by mgsloan** [comment]
LGTM, thanks!

**Comment by da-x** [comment]
This change helped to reveal that zip-archive disregards file modes from the original archived Git tree. I've [added a pull request](https://github.com/jgm/zip-archive/pull/26) for that matter in the relevant repository.

**Pull request merged**
