### PR TITLE
Implement getTerminalWidth for Windows

### PR DESCRIPTION
**Pull request by NeonGraal**
Please include the following checklist in your PR:

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

## Tests
I temporarily added a `putStrLn "!!!"` just before the `getWidth` call in `getTerminalWidth` to be sure that the function was being called.
I then ran the modified stack with `stack run stack -- ls stack-color` and got the "!!!"
To check the non-console case I ran the above command with the stdout and stderr redirected to files

### CODE REVIEW

**Comment by NeonGraal** [comment]
Resolve [3588](https://github.com/commercialhaskell/stack/issues/3588)

**Comment by snoyberg** [comment]
The last comment in the referenced issue (#3588) mentions the terminal-size library. Is there a reason you didn't go with that approach? My concern here is that this change introduces lower bounds on a few packages that ship with GHC, which we typically try to avoid doing.

**Comment by NeonGraal** [comment]
Ah. I went the way of upgrading an existing dependency rather than including a new one. Didn't realise the lower bounds issue.

At first look using the `terminal-size` package may actually allow me to delete some code.

Which would you prefer, I commit a revert here and then another with the new change or cancel this PR and raise a new one.

**Comment by snoyberg** [comment]
No strong preference to be honest, take your pick. If you pushed me for an answer, I'd probably lean towards new PR.

**Comment by NeonGraal** [comment]
Implemented better in [https://github.com/commercialhaskell/stack/pull/4797]

**Pull request closed without merging**
