### PR TITLE
Add `fast_finish` for Travis. Add fixups for #2659.

### PR DESCRIPTION
**Pull request by lwm**
If something goes wrong, fail faster.

### CODE REVIEW

**Comment by lwm** [comment]
Don't have time right now, but here are the failures:

```
# GHC 7.8.4
/home/travis/build/commercialhaskell/stack/src/Stack/Build/Cache.hs:340:33:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid),
      ‘FilePath.<.>’ (imported from System.FilePath),
      ‘</>’ (imported from Path)
```

```
# GHC 8.0.1
/Users/travis/build/commercialhaskell/stack/src/Stack/Ghci/Script.hs:17:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
```
Probably related to the merge of #2659?

**Comment by lwm** [comment]
I hope https://github.com/commercialhaskell/stack/pull/2688/commits/50821e126b4abf8795d9177f400dc0d9459c83b9 covers it? Not really used to write cross GHC code. @mgsloan, you mentioned a commit to remove this warning (https://github.com/commercialhaskell/stack/pull/2659#issuecomment-252395619), where was that?

**Comment by sjakobi** [comment]
Damn, didn't see that you were working on the compile failures too!

What does `fast_finish` do?

**Comment by lwm** [comment]
> Damn, didn't see that you were working on the compile failures too!

Ah, someone also fixed them? I will check changes and rebase when I get a chance. Just wanted to fix up issues caused by one of my PRs.

> What does fast_finish do?

It's pretty cool. Faster failure feedback, pretty much. From the docs:

> With fast finishing enabled, Travis CI will mark your build as finished as soon as one of two conditions are met: The only remaining jobs are allowed to fail, or a job has already failed.

**Comment by sjakobi** [comment]
> Ah, someone also fixed them?

I think I've caught most of them now, maybe all.

> > With fast finishing enabled, Travis CI will mark your build as finished as soon as one of two conditions are met: The only remaining jobs are allowed to fail, or a job has already failed.

When one job fails, are the other jobs canceled or are they allowed to finish? Our CI jobs often fail independently of each other so when one fails it's still good to know what happened to the other ones.

**Comment by lwm** [comment]
> When one job fails, are the other jobs canceled or are they allowed to finish?

They are allowed to finish. The build is simply reported as failure on the Github UI faster.

I rebased and added https://github.com/commercialhaskell/stack/pull/2688/commits/5dbee54ead9e0ec02c6dd914a2a48bd803bea2d1.

**Comment by mgsloan** [comment]
Thanks!

**Pull request merged**
