### PR TITLE
Fix #5697 Move stack to lts-19.16 (GHC 9.0.2) from lts-17.15 (GHC 8.10.4)

### LINKED ISSUE #5697: Move stack to lts-19.7 (GHC 9.0.2) from lts-17.15 (GHC 8.10.4)
`stack` aims to define a well-known combination of dependencies that the executable ships with and aims to support exactly one version of the `Cabal` library with each release of `stack`. (See  https://github.com/commercialhaskell/stack/pull/5696#issuecomment-1086678998)

The `stack.yaml` for `stack` currently specifies resolver `lts-17.15` (GHC 8.10.4), which includes `Cabal-3.2.1.0` and `aeson-1.5.6.0`. I propose a move to `lts-19.7` (GHC 9.0.2), the current LTS snapshot on Stackage, which includes `Cabal-3.4.1.0` and `aeson-2.0.3.0`.

`stack` currently builds with `lts-19.7` and two extra dependencies (see `stack-ghc-902.yaml`), after commit aa21f08925bb4bf5f3b6c6b595f8e718ef42c411.

This is motivated in part because GHC 8.10.4 is not one of the three current stable releases of GHC (which are 9.2.2, 9.0.2 and 8.10.7). (See https://www.haskell.org/ghc/download.html.)

Edit: Updated for bump from lts-19.1 to lts-19.3. Further updated for bumps to lts-19.4, lts-19.5, lts-19.6 and lts-19.7.

### PR DESCRIPTION
**Pull request by mpilgrem**
Also corrects a typo in `stack-ghc-902.yaml` comment.

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building, and using, `stack`.

### CODE REVIEW

**Comment by mpilgrem** [comment]
This revised pull request is now at the stage where the Windows-based tests (unit and integration) pass, but tests for other operating systems do not. I think that is because an updated 'docker' image is required, and I have raised an issue in the relevant repository.

To summarise my approach to tests, with some exceptions, I replaced references to LTS resolvers with `lts-19.6`, to nightly resolvers with `nightly-2022-03-17` (the most recent based on GHC 9.0.2), and to compilers with `ghc-9.0.2`. Where needed, I also bumped references to packages to be consistent with those changes.

A test using `StackTest.runRepl` failed because the directory `/tmp` (corresponding to `C:\tmp`) does not exist on Windows. I don't know how it succeeded before. I varied `runRepl` to use the Windows `TEMP` directory on Windows.

For test `4488-newer-cabal-version`, `stack` does not support `cabal-version: 3.6`, so I used `ghc-8.6.5` and `cabal-version: 3.4`. This required some `stack setup` in the test's `Main.hs`.

For test `4754-rebuild-haddocks`, GHC 9.0.2 tolerates invalid Haddocks. So, I added flags `-Winvalid-haddock` and `-Werror`.

For disabled test `cabal-subsidiary-dependency`, the CI now has GHC >= 8.8.1, so I reintroduced the test.

For test `internal-libraries`, I understand that an upstream bug in Cabal means that the test must be run with GHC < 9. So, some `stack setup` is required in the test's `Main.hs`.

**Comment by mpilgrem** [comment]
In respect of the CI on Unix-like operating systems, at https://github.com/fpco/alpine-haskell-stack/issues/5#issuecomment-1126898934 a kind offer has been made to enable a GHC 9.0.2 docker image in DockerHub, if somebody can send a pull request for it. The PR should target this branch: https://github.com/fpco/alpine-haskell-stack/tree/ghc902. Also, the latest stable alpine (possibly version 3.15.4) should be used as the base image.

Can anybody reading this assist?

**Comment by mpilgrem** [comment]
The problem with the macOS integration tests, is things like this (extract):
~~~
2022-05-19T20:37:04.1854590Z Running integration test 1/108: 111-custom-snapshot
...
2022-05-19T20:37:12.1068550Z Failure, dumping log
2022-05-19T20:37:12.1069450Z 
2022-05-19T20:37:12.1069890Z 
2022-05-19T20:37:12.1070410Z Running: /Users/runner/work/stack/stack/_release/bin/stack-2.7.6-osx-x86_64/stack build
2022-05-19T20:37:12.1072480Z No compiler found, expected minor version match with ghc-9.0.2 (x86_64) (based on resolver setting in /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/stack-integration-111-custom-snapshot84196/stack.yaml).
2022-05-19T20:37:12.1074470Z To install the correct GHC into /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/home84196/.stack/programs/x86_64-osx/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
2022-05-19T20:37:12.1075420Z Main.hs: Exited with exit code: ExitFailure 1
2022-05-19T20:37:12.1075850Z CallStack (from HasCallStack):
2022-05-19T20:37:12.1076420Z   error, called at /Users/runner/work/stack/stack/test/integration/lib/StackTest.hs:63:34 in main:StackTest
2022-05-19T20:37:12.1077430Z   stack, called at /Users/runner/work/stack/stack/test/integration/tests/111-custom-snapshot/Main.hs:4:8 in main:Main
2022-05-19T20:37:12.1077840Z 
2022-05-19T20:37:12.1077850Z 
2022-05-19T20:37:12.1078160Z End of log for 111-custom-snapshot
~~~
It is looking for GHC 9.0.2 and not finding it, including at `/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/home84196/.stack/programs/x86_64-osx/`.

I think this part of `IntegrationSpec.runApp` is relevant, which turns off `install-ghc` and turns on `system-ghc`:
~~~haskell
app = App
  { appSimpleApp = simpleApp
  , appRunghc = runghc
  , appLibDir = libdir
  , appSetupHome = \inner' -> withSystemTempDirectory "home" $ \newHome -> do
    let newStackRoot = newHome </> ".stack"
    createDirectoryIfMissing True newStackRoot
    let modifyEnv'
      = Map.insert "HOME" (fromString newHome)
      . Map.insert "APPDATA" (fromString newHome)
      . Map.insert "STACK_ROOT" (fromString newStackRoot)
      writeFileBinary (newStackRoot </> "config.yaml") "system-ghc: true\ninstall-ghc: false\n"
      withModifyEnvVars modifyEnv' inner'
  , appTestDirs = testDirs
  }
~~~
What I can't currently identify is: where in the `.github/workflows/integration-tests.yml` does the 'system GHC' get installed? And why is this a problem for `macos-latest` but not `windows-latest`?

**Comment by mpilgrem** [comment]
Where might it be looking for the 'system GHC'? There is also this in the log (extract, edited). `/Users/runner/.stack/programs/x86_64-osx/ghc-9.0.2/bin` is listed twice on the `PATH`. If `stack` had downloaded GHC 9.0.2, that is where I would have expected it to be located:
~~~
2022-05-19T20:37:04.1736460Z Running with the following environment
2022-05-19T20:37:04.1850410Z PATH=
/Users/runner/work/stack/stack/.stack-work/install/x86_64-osx/c21b03e833d0f8566cef88c397ff86d1a1a5567592b3c036d828f6b947f69917/9.0.2/bin
:/Users/runner/.stack/snapshots/x86_64-osx/c21b03e833d0f8566cef88c397ff86d1a1a5567592b3c036d828f6b947f69917/9.0.2/bin
:/Users/runner/.stack/compiler-tools/x86_64-osx/ghc-9.0.2/bin
:/Users/runner/.stack/programs/x86_64-osx/ghc-9.0.2/bin
:/Users/runner/.stack/.stack-work/install/x86_64-osx/2c8263ac1a4099533510145f928c08a1d3efea9eeba0f5f3ae1c0e3d06594b6d/9.0.2/bin
:/Users/runner/.stack/snapshots/x86_64-osx/2c8263ac1a4099533510145f928c08a1d3efea9eeba0f5f3ae1c0e3d06594b6d/9.0.2/bin
:/Users/runner/.stack/compiler-tools/x86_64-osx/ghc-9.0.2/bin
:/Users/runner/.stack/programs/x86_64-osx/ghc-9.0.2/bin
:/usr/local/lib/ruby/gems/2.7.0/bin
:/usr/local/opt/ruby@2.7/bin
:/usr/local/opt/pipx_bin
:/Users/runner/.cargo/bin
:/usr/local/opt/curl/bin
:/usr/local/bin:/usr/local/sbin
:/Users/runner/bin
:/Users/runner/.yarn/bin
:/Users/runner/Library/Android/sdk/tools
:/Users/runner/Library/Android/sdk/platform-tools
:/Users/runner/Library/Android/sdk/ndk-bundle
:/Library/Frameworks/Mono.framework/Versions/Current/Commands
:/usr/bin:/bin:/usr/sbin
:/sbin
:/Users/runner/.dotnet/tools
:/Users/runner/.ghcup/bin
:/Users/runner/hostedtoolcache/stack/2.7.5/x64
~~~

**Comment by mpilgrem** [comment]
I've added something to `integration-tests.yml` to reveal all `ghc` in the stack environment (which itself triggers the download of GHC 9.0.2 to the usual place). I think the original problem may be something to do with this: `macos-latest` and `ubuntu-latest` come with GHCup 0.1.17.8 and `.ghcup/bin/ghc`, while `windows-latest` does not. I think, somehow, that means that `stack etc/scripts/release.hs check` was not triggering `stack` to download GHC 9.0.2 into the usual place before the tests were run.

**Comment by mpilgrem** [comment]
The macOS integration tests are still failing (in the same way), despite the fact that GHC 9.0.2 should be on the `PATH`:
~~~
2022-05-21T19:39:08.7565890Z Installing GHC ...
2022-05-21T19:39:23.2448460Z Installed GHC.
2022-05-21T19:39:26.4418450Z /Users/runner/.stack/programs/x86_64-osx/ghc-9.0.2/bin/ghc
2022-05-21T19:39:26.4418780Z /Users/runner/.ghcup/bin/ghc
~~~

**Comment by mpilgrem** [comment]
I am going to temporarily modify `111-custom-snapshot/Main.hs` to see if that helps diagnose the `macos-latest` CI problem, to:
~~~haskell
import StackTest

main :: IO ()
main = do
  stack ["--verbose", "build"]
~~~

**Comment by mpilgrem** [comment]
If I build `stack` with `process-1.6.14.0` (locally, on macOS 10.15.5), I get the same problem but with a different error message: `... ghc-pkg-9.0.2: startProcess: posix_spawnp: invalid argument (Bad file descriptor)`, this follows `Run process: /Users/ ... /.stack/programs/x86_64-osx/ghc-9.0.2/bin/ghc-pkg-9.0.2 --global -no-user-package-db dump --expand-pkgroot`.

**Comment by mpilgrem** [comment]
The error is flowing from this line in `Stack.Setup.pathsFromCompiler`:
~~~haskell
globalDump <- withProcessContext menv $ globalsFromDump pkg
~~~
which leads, via `Stack.SourceMap.globalsFromDump` and `Stack.PackageDump.ghcPkgDump` and `Stack.PackageDump.ghcPkgCmdArgs` to `Stack.Prelude.sinkProcessStdout`.

**Comment by mpilgrem** [comment]
`Stack.Prelude.sinkProcessStdout` includes the comment: 'Should not be used for long-running processes or ones with lots of output; for that use `sinkProcessStderrStdout`'. So, I am going to try substituting that function into `Stack.PackageDump.ghcPkgCmdArgs`.

**Comment by psibi** [comment]
I just saw this PR, I have been working on similar one but for GHC 9.2.2. I will see if I can merge your changes to my branch.

**Comment by mpilgrem** [comment]
As GHC 9.2.2 is said to be broken for some Windows users, I was waiting for GHC 9.2.3 to reach a Stackage resolver, and then to see if that version of GHC worked for all the important operating systems.

**Comment by mpilgrem** [comment]
@psibi, my sticking point on this pull request is getting the non-Windows CI to work. In the case of macOS, my current hypothesis is that there is an upstream issue with the `process` library.

**Comment by psibi** [comment]
Ah, I see. My plan is to get GHC 9.2.2 working and then move to GHC 9.2.3. I'm hoping that the it wouldn't be a huge change to migrate to 9.2.3.

> I see that nightly-2022-06-08 is based on GHC 9.2.3.

Yeah, it seems to have appeared from today. If not, I would have started my work based out of GHC 9.2.3.

> my sticking point on this pull request is getting the non-Windows CI to work. In the case of macOS, my current hypothesis is that there is an upstream issue with the process library - and I have posted an issue in its repository.

I just read your issue. That looks tricky and this migration seems more challenging that I estimated.

**Comment by psibi** [comment]
@mpilgrem I have been working on directly adding support for GHC 9.2.3 now. Can you see why some integration tests fail for the windows environment: https://github.com/commercialhaskell/stack/runs/6832464770?check_suite_focus=true ?

It seems it's for these three tests:

```
Failed tests:
- internal-libraries - ExitFailure 1
- module-added-multiple-times - ExitFailure 1
- override-compiler - ExitFailure 1
```

I will debug the MacOS failure on Monday further. I have the integration tests passing fine for Linux (atleast for GHC 9.2.2) and I have to just build a new Docker image to get that fixed. So in summary I think these are the things that are blocking for the new release:

- Debug MacOS issue
- Investigate the three integration test failures for Windows.

**Comment by mpilgrem** [comment]
@psibi, on the three integration tests failing under Windows:

`internal-libraries` - see my added comment in `test/integration/tests/internal-libraries/files/stack.yaml`. I understand this to be an upstream issue with the `Cabal` library, affecting GHC 9.0 and 9.2. In the test, I used resolver `ghc-8.10.7` and included a `stack ["setup"]` in the `Main.hs`.

`module-added-multiple-times` - I diagnosed this as a bug in `test/integration/lib/StackTest.hs` at about line 122. `withFile "/tmp/stderr" WriteMode` is referring to a directory that does not exist on Windows - I do not know why the code worked pre-GHC 9.0. I replaced the line with:
~~~haskell
tempDir <- if isWindows
                then fromMaybe "" <$> lookupEnv "TEMP"
                else return "/tmp"
let tempFP = tempDir ++ "/stderr"

_ <- forkIO $ withFile tempFP WriteMode
~~~

`override-compiler` - Did you update the logic in line 7 of `test/integration/tests/override-compiler/Main.hs`? For GHC 9.2.3, it should read as `unless (concat (lines ver) == "9.2.3") $ error $ "Invalid version: " ++ show ver`.

**Comment by psibi** [comment]
@mpilgrem Thanks for the various hints, I will try to apply them on Monday.

> Did you update the logic in line 7 of test/integration/tests/override-compiler/Main.hs? For GHC 9.2.3, it should read as unless (concat (lines ver) == "9.2.3") $ error $ "Invalid version: " ++ show ver.

Yeah, I think did because I have the integration test suite passing for Linux GHC 9.2.2.

Alsp, possibly do you think you can send the windows fixes (suggested above) to my branch (unless you want me to take your specifc fixes here, but I think it will lose your commit information) ? I think there is a quite a overlap in both of our PR, sorry for not collaborating with you earlier. I saw your PR after I started working on GHC 9.2.2 support.

Proving the above window fixes work, I think there is only one remaning unresolved thing - to figure out the MacOS integration test suite failure. I'm planning into look into it on coming Monday, but since I don't have access to a Mac machine, it might be challenging for me.

**Comment by psibi** [comment]
> Yeah, I think did because I have the integration test suite passing for Linux GHC 9.2.2.

I was wrong. I just did the update for GHC 9.2.2 and not for 9.2.3. I guess fixing that should be trivial then. Thanks!

**Comment by mpilgrem** [comment]
Closing, as overtaken by #5763 (move Stack to GHC 9.2.4).

**Pull request closed without merging**
