### PR TITLE
More hlint suggested clean ups

### PR DESCRIPTION
**Pull request by lwm**
Follow on from  #2606 and working on #2592. 

Covers:
  - [x] Unused pragmas
  - [x] Redundant ~~do~~, guard, $, bracket and return

Lots of formatting noise on this one too :bomb:.

### CODE REVIEW

**Comment by mgsloan** [comment]
Unused pragmas, sure, but honestly I'm on the wall on most of these hlint opinions.  Redundant do is fine in circumstances where you are working in a monad and anticipate the future need of additional statements.  But I suppose that may just be my idiosyncratic preference.  In other words, we do not expect our code base to pass hlint without warnings.

Did this take work to implement?  I am leaning towards closing the PR.  Thoughts, @sjakobi ?

**Comment by mgsloan** [comment]
On second thought, heck, if it reduces your hlint warnings and if those are on by default, we may as well.

**Comment by lwm** [comment]
@sjakobi Given https://github.com/commercialhaskell/stack/pull/2591#issuecomment-248809797 (and also your recommendation @mgsloan), I will ignore the redundant do notation hints and revert the indentation changes.

**Comment by mgsloan** [comment]
Thanks, that sounds great @lwm!  We appreciate your efforts :)

**Comment by lwm** [comment]
OK, here comes the rebased and revised version :beers:

**Comment by lwm** [comment]
[Failure](https://travis-ci.org/commercialhaskell/stack/jobs/163791813) is (GHC 7.10.3): 

> ...src/Stack/PackageDump.hs:118:12: Warning: 
> Failed to find cabal file, in order to resolve relative paths in TH. 
> Using current working directory instead. 
> Failing due to -Werror.

Not sure if this is unrelated? I didn't touch that file ...

**Comment by sjakobi** [comment]
I have restarted the failing job.

The changes look good to me now!

**Comment by sjakobi** [comment]
Ok, that Travis job errored now due to the current stackage.org outage. I'm merging anyway.

Thanks!

**Comment by lwm** [comment]
:rocket:

**Pull request merged**
