### PR TITLE
Update package.yaml, not .cabal file

### PR DESCRIPTION
**Pull request by trotha01**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by mattaudesse** [comment]
Thanks @trotha01 but I think this section actually needs to remain as written since not everyone uses `package.yaml`.

Alternatively (and maybe you'd like to update the PR to show this?) we could explain how both work and note that `package.yaml`'s contents will automatically generate the cabal file at build time if present.

**Comment by trotha01** [comment]
From what I understand, the default flow, for the current stable version, is to update package.yaml. Especially since it says this later in the docs:

> Since Stack 1.6.1, the package.yaml is the preferred package format that is provided built-in by stack through the hpack tool. The default behaviour is to generate the .cabal file from this package.yaml, and accordingly you should not modify the .cabal file.


Given that this is the quickstart guide, it seems like we should point people to updating package.yaml and leave manual edits to the autogenerated .cabal file be a special case (which we can link to if you like). Especially since a Warning is given if users edit the .cabal file. The warning can be confusing to new users of stack.
```
Warning: <path>/<project>.cabal was modified manually. Ignoring <path>/package.yaml in favor of the cabal
         file. If you want to use the package.yaml file instead of the cabal file, then please delete the cabal file.
```

**Comment by mattaudesse** [comment]
Yeah, I think you're right that we should lean toward `package.yaml` as long as we don't confuse the people who don't have one.

Consider the case of somebody who uses the `simple` template to bootstrap a new project:

```bash
--> stack new beginner-proj simple
Downloading template "simple" to create project "beginner-proj" in beginner-proj/ ...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- beginner-proj/

Selecting the best among 14 snapshots...

* Matches lts-12.9

Selected resolver: lts-12.9
Initialising configuration using resolver: lts-12.9
Total number of user packages considered: 1
Writing configuration to file: beginner-proj/stack.yaml
All done.

--> tree beginner-proj/
beginner-proj/
├── LICENSE
├── README.md
├── Setup.hs
├── beginner-proj.cabal
├── src
│   └── Main.hs
└── stack.yaml

1 directory, 6 files
```

As long as there's some quick blurb to note the difference I think we're good:
> if you're using a `package.yaml` then ...; otherwise, ...

Thanks again for catching this.

**Comment by trotha01** [comment]
I ended up adding the information as a separate bullet point since the Quickstart Guide starts with the command `stack new my-project`. Let me know if that works. Thanks for the help.

**Comment by mattaudesse** [comment]
Cool, thanks @trotha01.

**Pull request merged**
