### PR TITLE
Show download progress via chattyDownload

### LINKED ISSUE #561: ghc download reports bytes without an indication of when it will be finished
I found the byte count odd although it provided a small comfort to know that something was downloading and not completely stuck.
Given that the byte count demonstrates progress immediately, it may be a good idea to keep it.

But it would be better to also indicate when the end will occur. This could be show a % of total size. Just a count of the MB size of the current download would help out a bit also.

### PR DESCRIPTION
**Pull request by markus1189**
Resolves #561.

Changes:
- add `Maybe Integer` argument to progress sink of `verifiedDownload`, where `Nothing` means the total is unknown
- add `bytes` formatter and the `formatting` library as an **additional dependency**
- add progress output to `chattyDownload`

Output looks like this:
```
λ> do man <- newManager; dir <- parseAbsFile "/tmp/7z.exe"; runStdoutLoggingT $ flip runReaderT man $ chattyDownload "7z" "http://7-zip.org/a/7z1505-x64.exe" dir
[sticky] Preparing to download 7z ... 
[Debug] Downloading from http://7-zip.org/a/7z1505-x64.exe to /tmp/7z.exe ... 
[sticky] 7z: download has begun 
[sticky] 7z: 47.55 KiB / 1.27 MiB (3.66%) downloaded... 
[sticky] 7z: 97.74 KiB / 1.27 MiB (7.51%) downloaded... 
[sticky] 7z: 186.77 KiB / 1.27 MiB (14.36%) downloaded... 
[sticky] 7z: 233.18 KiB / 1.27 MiB (17.93%) downloaded... 
[sticky] 7z: 279.58 KiB / 1.27 MiB (21.50%) downloaded... 
[sticky] 7z: 325.99 KiB / 1.27 MiB (25.06%) downloaded... 
[sticky] 7z: 372.39 KiB / 1.27 MiB (28.63%) downloaded... 
[sticky] 7z: 418.80 KiB / 1.27 MiB (32.20%) downloaded... 
[sticky] 7z: 465.21 KiB / 1.27 MiB (35.77%) downloaded... 
[sticky] 7z: 511.61 KiB / 1.27 MiB (39.34%) downloaded... 
[sticky] 7z: 558.02 KiB / 1.27 MiB (42.90%) downloaded... 
[sticky] 7z: 604.43 KiB / 1.27 MiB (46.47%) downloaded... 
[sticky] 7z: 650.83 KiB / 1.27 MiB (50.04%) downloaded... 
[sticky] 7z: 697.24 KiB / 1.27 MiB (53.61%) downloaded... 
[sticky] 7z: 743.64 KiB / 1.27 MiB (57.18%) downloaded... 
[sticky] 7z: 790.05 KiB / 1.27 MiB (60.74%) downloaded... 
[sticky] 7z: 836.46 KiB / 1.27 MiB (64.31%) downloaded... 
[sticky] 7z: 882.86 KiB / 1.27 MiB (67.88%) downloaded... 
[sticky] 7z: 929.27 KiB / 1.27 MiB (71.45%) downloaded... 
[sticky] 7z: 975.68 KiB / 1.27 MiB (75.02%) downloaded... 
[sticky] 7z: 1022.08 KiB / 1.27 MiB (78.58%) downloaded... 
[sticky] 7z: 1.03 MiB / 1.27 MiB (81.36%) downloaded... 
[sticky] 7z: 1.11 MiB / 1.27 MiB (87.63%) downloaded... 
[sticky] 7z: 1.27 MiB / 1.27 MiB (100.00%) downloaded... 
[sticky-done] Downloaded 7z. 
```

### CODE REVIEW

**Comment by snoyberg** [comment]
This PR looks great (as usual per your proven quality standards). Unfortunately, there's one problem: we can't use the `formatting` package due to issues with compiling some of its dependencies on Windows. How difficult would it be to rewrite this to avoid usage of `formatting`?

**Comment by snoyberg** [comment]
Just do give you an idea of the error message on Windows:

```
<command line>: can't load .so/.DLL for: stdc++.dll (addDLL: could not load DLL)
ghc.exe: stdc++: The specified module could not be found.
Loading package double-conversion-2.0.1.0 ...
Completed all 7 actions.

--  While building package stack-0.1.2.1 using:
      C:\\Users\\Michael\\AppData\\Local\\Programs\\stack\\i386-windows\\ghc-7.8.4\\bin\\runhaskell.exe -package=Cabal-1.18.1.5 -clear-package-db -global-package-db -package-db=C:\Users\Michael\AppData\Roaming\stack\snapshots\i386-windows\lts-2.17\7.8.4\pkgdb\ C:\Users\Michael\AppData\Local\Temp\stack4324\Setup.hs --builddir=.stack-work\dist\i386-windows\Cabal-1.18.1.5\ build
    Process exited with code: ExitFailure 1
```

**Comment by markus1189** [comment]
Aw what a shame :).  So the problem seems to be the C++ library `double-conversion` and the dependency chain: `formatting -> text-format -> double-conversion`.

I replaced the use of `formatting` with `Text.printf`, which also works.  And I aligned the numbers such that there is no horizontal jumping of the width:

```
λ> do man <- newManager; dir <- parseAbsFile "/tmp/7z.exe"; runStdoutLoggingT $ flip runReaderT man $ chattyDownload "7z" "http://7-zip.org/a/7z1505-x64.exe" dir
[sticky] Preparing to download 7z ... 
[Debug] Downloading from http://7-zip.org/a/7z1505-x64.exe to /tmp/7z.exe ... 
[sticky] 7z: download has begun 
[sticky] 7z:   15.21 KiB / 1.27 MiB (  1.17%) downloaded... 
[sticky] 7z:   43.33 KiB / 1.27 MiB (  3.33%) downloaded... 
[sticky] 7z:   85.52 KiB / 1.27 MiB (  6.58%) downloaded... 
[sticky] 7z:  131.93 KiB / 1.27 MiB ( 10.14%) downloaded... 
[sticky] 7z:  178.33 KiB / 1.27 MiB ( 13.71%) downloaded... 
[sticky] 7z:  224.74 KiB / 1.27 MiB ( 17.28%) downloaded... 
[sticky] 7z:  271.14 KiB / 1.27 MiB ( 20.85%) downloaded... 
[sticky] 7z:  317.55 KiB / 1.27 MiB ( 24.42%) downloaded... 
[sticky] 7z:  363.96 KiB / 1.27 MiB ( 27.98%) downloaded... 
[sticky] 7z:  407.55 KiB / 1.27 MiB ( 31.34%) downloaded... 
[sticky] 7z:  453.96 KiB / 1.27 MiB ( 34.90%) downloaded... 
[sticky] 7z:  500.36 KiB / 1.27 MiB ( 38.47%) downloaded... 
[sticky] 7z:  546.77 KiB / 1.27 MiB ( 42.04%) downloaded... 
[sticky] 7z:  593.18 KiB / 1.27 MiB ( 45.61%) downloaded... 
[sticky] 7z:  613.83 KiB / 1.27 MiB ( 47.20%) downloaded... 
[sticky] 7z:  698.21 KiB / 1.27 MiB ( 53.68%) downloaded... 
[sticky] 7z:  775.99 KiB / 1.27 MiB ( 59.66%) downloaded... 
[sticky] 7z:  822.39 KiB / 1.27 MiB ( 63.23%) downloaded... 
[sticky] 7z:  967.24 KiB / 1.27 MiB ( 74.37%) downloaded... 
[sticky] 7z: 1008.02 KiB / 1.27 MiB ( 77.50%) downloaded... 
[sticky] 7z:    1.03 MiB / 1.27 MiB ( 81.07%) downloaded... 
[sticky] 7z:    1.08 MiB / 1.27 MiB ( 84.64%) downloaded... 
[sticky] 7z:    1.09 MiB / 1.27 MiB ( 85.50%) downloaded... 
[sticky] 7z:    1.25 MiB / 1.27 MiB ( 98.77%) downloaded... 
[sticky] 7z:    1.27 MiB / 1.27 MiB (100.00%) downloaded... 
[sticky-done] Downloaded 7z. 
```

**Comment by chrisdone** [comment]
Looks good to me. I think I'll steal that `bytes` formatter and put it in the formatting package, even though we can't use it here.

**Comment by DanBurton** [comment]
:+1: pretty!

**Comment by snoyberg** [comment]
Awesome, thank you!

**Comment by gregwebs** [comment]
Thanks! These small things go a long way to making a great user experience.

**Pull request merged**
