### PR TITLE
Move Stack to lts-20.13 (GHC 9.2.7)

### PR DESCRIPTION
**Pull request by mpilgrem**
* [x] Any changes that could be relevant to users have been recorded in ChangeLog.md.
* [x] The documentation has been updated, if necessary

Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI.

### CODE REVIEW

**Comment by hasufell** [comment]
You should wait for 9.2.7. 9.2.6 has bugs on windows: https://gitlab.haskell.org/ghc/ghc/-/issues/22961

9.2.7 will be released shortly'

**Comment by mpilgrem** [comment]
@hasufell, thanks for pointing that out. My intention was to keep pace with the most recent Stackage LTS Haskell snapshot. I'll look out for GHC 9.2.7.

**Comment by juhp** [comment]
I wish it was a little easier to track these things... (really comment to ghc)

**Comment by mpilgrem** [comment]
@psibi, please could you create a docker image for GHC 9.2.7? (If you also have time to document how you do that, that would be much appreciated.)

**Comment by psibi** [comment]
@mpilgrem I have pushed a newer image here:

```
fpco/alpine-haskell-stack:9.2.7
```

I have also update the docs here: https://github.com/fpco/alpine-haskell-stack

Let me know if something isn't clear and I will try to update the docs.

**Comment by mpilgrem** [comment]
@psibi, many thanks!

**Pull request merged**
