### PR TITLE
Build on travis with stack too

### PR DESCRIPTION
**Pull request by phadej**
Resolves https://github.com/commercialhaskell/stack/issues/1398

### CODE REVIEW

**Comment by phadej** [comment]
Done. ping @snoyberg @borsboom 

- Uses compiler hack to have separate caches for each matrix row
- osx build as an extra

**Comment by mgsloan** [comment]
Thanks!  LGTM, I'm in favor of merging.  Seem good, @borsboom ?

**Comment by borsboom** [comment]
It looks like this also re-enables running the integration tests.  In the past, we've had trouble with Travis timing out the builds when those are enabled.  I'll merge as-is and we'll see how it goes, but may have to disable the integration tests if they cause problems.

**Comment by phadej** [comment]
@borsboom it doesn't enabled integration tests, they use "comment trick"
```sh
% true echo foo
# does nothing
```

**Comment by borsboom** [comment]
Ah I see, I saw they were uncommented but didn't look more closely.

**Pull request merged**
