### PR TITLE
Fix #6142 Build statically-linked Linux/Aarch64 Stack

### LINKED ISSUE #6142: Provide statically linked binary for Linux/AArch64
The binary for Linux/x86_64 is statically linked

```bash
$ stack --version
Version 2.11.1, Git revision c1167a6abc3f4978ccded5ba0246a57387da0e2f x86_64 hpack-0.35.2
$ file /usr/local/bin/stack 
/usr/local/bin/stack: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

whereas the binary for Linux/AArch64 is not.

```bash
$ stack --version
Version 2.11.1, Git revision c1167a6abc3f4978ccded5ba0246a57387da0e2f aarch64 hpack-0.35.2
$ file /usr/local/bin/stack
/usr/local/bin/stack: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[xxHash]=3d8f9d614342c40f, stripped
```

### PR DESCRIPTION
**Pull request by mpilgrem**
This pull request is draft while I experiment with the CI.

* [x] Any changes that could be relevant to users have been recorded in ChangeLog.md.
* [x] The documentation has been updated, if necessary

Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI.

### CODE REVIEW

**Comment by mpilgrem** [comment]
@benz0li, I have probably got the wrong end of the stick, but I thought I could simply use the Stack that comes with the self-hosted Linux Aarch64 runner to run `stack etc/scripts/release.hs build --alpine`, which would then build Stack in your `glcr.b-data.ch/ghc/ghc-musl:9.2.8` Docker container. However, it falls over with (extracts):
~~~text
...
Error: [S-7282]
       Stack failed to execute the build plan.
       
       While executing the build plan, Stack encountered the error:
       
       [S-7011]
       While building package digest-0.0.1.7 (scroll up to its section to see the error) using:
...
~~~ 

I tend to associate problems with building `digest-0.0.1.7` with a missing `pkg-config` dependency. May I ask, does your Docker container come with `pkg-config`? If it does not, could it be modified to supply it?

**Comment by benz0li** [comment]
> May I ask, does your Docker container come with `pkg-config`? If it does not, could it be modified to supply it?

The package `pkgconfig` is already available in the image.

**Comment by benz0li** [comment]
Stack builds fine using `glcr.b-data.ch/ghc/ghc-musl:9.6.2`:

## Host

```
docker run --rm -ti glcr.b-data.ch/ghc/ghc-musl:9.2.8 bash
```

## Docker container

```
cd /tmp && git clone https://github.com/commercialhaskell/stack.git
```

```
Cloning into 'stack'...
remote: Enumerating objects: 66913, done.
remote: Counting objects: 100% (6851/6851), done.
remote: Compressing objects: 100% (1010/1010), done.
remote: Total 66913 (delta 5950), reused 6472 (delta 5796), pack-reused 60062
Receiving objects: 100% (66913/66913), 22.37 MiB | 17.51 MiB/s, done.
Resolving deltas: 100% (46648/46648), done.
```

```bash
cd stack && stack install stack --flag=stack:static --no-install-ghc --system-ghc
```

### Build log

[build_log.txt](https://github.com/commercialhaskell/stack/files/12385095/build_log.txt)

**Comment by benz0li** [comment]
With Stack v2.11.1 installed on the host, I am able to build Stack v2.12.0 (`master`) using `stack install stack --docker --docker-stack-exe=image --flag=stack:static --no-install-ghc --system-ghc` for both Linux/x86_64 and Linux/AArch64.

**Comment by benz0li** [comment]
@mpilgrem Using the same steps for Linux/AArch64 as for Linux/x86_64 should give the same result.

Both images are built with the same Dockerfile: https://gitlab.b-data.ch/ghc/ghc-musl/-/blob/main/prior/9.2.8.Dockerfile

**Comment by benz0li** [comment]
```
docker run --rm -ti glcr.b-data.ch/ghc/ghc-musl:9.2.8 bash -c 'uname -m && which pkg-config && pkg-config --version'
```

```
aarch64
/usr/bin/pkg-config
1.8.1
```

**Comment by benz0li** [comment]
@mpilgrem I do not see the `glcr.b-data.ch/ghc/ghc-musl:9.2.8` image getting pulled: https://pipelines.actions.githubusercontent.com/serviceHosts/4fdad996-cbc4-4b05-9917-c90ede306da1/_apis/pipelines/1/runs/6868/signedlogcontent/12?urlExpires=2023-08-19T11%3A46%3A39.3000157Z&urlSigningMethod=HMACV1&urlSignature=O3egR%2B9y6CIqXm6lgVVE21R3M0t6r1Dd%2FZGxBmsA2Zs%3D (https://pipelines.actions.githubusercontent.com/serviceHosts/4fdad996-cbc4-4b05-9917-c90ede306da1/_apis/pipelines/1/runs/6868/signedlogcontent/12?urlExpires=2023-08-19T11%3A46%3A39.3000157Z&urlSigningMethod=HMACV1&urlSignature=O3egR%2B9y6CIqXm6lgVVE21R3M0t6r1Dd%2FZGxBmsA2Zs%3D)

Please compare to Linux/x86_64 https://pipelines.actions.githubusercontent.com/serviceHosts/4fdad996-cbc4-4b05-9917-c90ede306da1/_apis/pipelines/1/runs/6843/signedlogcontent/4?urlExpires=2023-08-19T11%3A46%3A11.8321831Z&urlSigningMethod=HMACV1&urlSignature=T90S72Q1RI3nZtTKs5fJtydJKLnVbjown8tll2aJU%2Bs%3D (https://github.com/commercialhaskell/stack/actions/runs/5902373180/job/16010287622)

**Comment by mpilgrem** [comment]
@benz0li, thanks for your help, and patience. The `pkg-config` was a problem with the self-hosted runner's software. `--docker-stack-exe=image` was missing from my Docker set up. I think I am almost there ...

**Comment by benz0li** [comment]
> @benz0li, thanks for your help, and patience.

No worries. Thank you for looking into this.

> The `pkg-config` was a problem with the self-hosted runner's software.

OK.

> `--docker-stack-exe=image` was missing from my Docker set up. I think I am almost there ...

ℹ️ After a new release I will update Stack in the images asap.

**Pull request merged**
