### PR TITLE
Support -ferror-spans syntax in GHC error messages

### PR DESCRIPTION
**Pull request by danald**

### CODE REVIEW

**Comment by sjakobi** [comment]
I have restarted the failing OS X build.

**Comment by sjakobi** [comment]
> I have restarted the failing OS X build.

I've restarted the OS X job once again.

**Comment by sjakobi** [comment]
@danald: I'm sorry that your PR has been languishing for so long. The core maintainers appear to be very busy right now.

I'm afraid I'm not very experienced with this part of the code and can't easily tell if it works or not.

Would you mind adding two short test cases for the two error formats in `src/test/Stack/Build/ExecuteSpec.hs`? A short comment on the formats in the code itself would be good too.

I'll simply merge the PR if the tests pass.

**Comment by borsboom** [comment]
This looks good to me, so I agree with merging once the test cases are in place.

**Comment by mgsloan** [comment]
Works for me, I think we can skip tests.  ExecuteSpec is essentially empty!  Might belong as an integration test if ghc actually gets invoked.

**Pull request merged**
