### PR TITLE
Print latest applicable version of packages on conflicts #508

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
So, I'm pretty sure this works as intended, but I've had a hard time finding an actual test case.

@bergmark, could you possibly give this one a try or maybe point me at the project you used in the example for #508?

**Comment by bergmark** [comment]
Looks good to me, thanks!

You can test it by putting `foo-1.0` in your stack.yaml and adding an upper bound `foo < 1` in a project's cabal file. This simulates that a package hasn't updated to a newer version of a dependency.

**Comment by sjakobi** [comment]
Thanks for the explanation, @bergmark!

Seems to work alright:
```
$ stack build
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      vector: needed (<0.10), couldn't resolve its dependencies
    needed for package: appl-0.1.0.0

--  Failure when adding dependencies:    
      primitive: needed (>=0.5.0.1 && <0.6), 0.6.1.0 found (latest applicable is 0.5.4.0)
    needed for package: vector-0.10.12.2
```

**Comment by mgsloan** [comment]
LGTM, thanks!

**Pull request merged**
