### PR TITLE
Add Alpine Linux specific processing

### PR DESCRIPTION
**Pull request by gliptak**
WIP Updates to get-stack

### CODE REVIEW

**Comment by mgsloan** [comment]
By WIP do you mean that this shouldn't be merged yet?  Also, I trust that these scripts are being tested (not going to try it myself).  Thanks for working on this

**Comment by gliptak** [comment]
Sorry for being imprecise. I did test these script changes, and they worked except as captured at https://github.com/commercialhaskell/stack/issues/2717

**Comment by gliptak** [comment]
Could this still be committed? It does improve Alpine Linux support ...

**Comment by mgsloan** [comment]
Sure, merging!

**Pull request merged**
