### PR TITLE
Don't watch files for non-library components that are not being built

### PR DESCRIPTION
**Pull request by tswelsh**
Attempt at a fix for #3483, following the comment there.  I'm not quite up on the internals of stack so let me know if this is the wrong direction. It raised a couple of questions about how things work, which may make it into their own issues.  One in particular: is the library component of a package always built, regardless of targets?

Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by tswelsh** [comment]
Just realised I had the checklist etc but hadn't actually done it.  How I tested: I used a project with a single package with an executable and test suite.  Ran `stack build --file-watch`, edited the test suite `Main.hs` and observed no rebuild.  Edited the executable's main file and it did rebuild.

**Comment by snoyberg** [comment]
This looks OK, and I've approved, but just doing a little more testing. I noticed some strange behavior, not sure if it's this patch or something else.

**Comment by mgsloan** [comment]
Hmm, I'm stumped.  Haven't tried to reproduce it, but the change looks good.  In particular:

* This should only affect `lpFiles`, and it is only used for file watching.

* Otherwise, it seems just like an inlining of `getPackageFilesSimple`, along with selection of which components to build.

Curious!

**Comment by tswelsh** [comment]
OK, I have reproduced the issue spotted by @snoyberg.  I believe the `unregistering (local file changes: ... )` is due to a call to `checkForUnlistedFiles`, called by `postBuildCheck`, within `Stack.Build.Execute.singleBuild`.  This ultimately uses `getPackageFilesSimple` which gets all files including those to do with test suites.  As the test suite files aren't in the build cache, they get added by this check and appear to be dirty the next time round, even though they aren't being used.  Phew!

I've added a commit which uses the same logic in both places, so the ultimate effect of all the changes is more or less to replace `getPackageFilesSimple` with a new, pickier function `getPackageFilesForTargets`.

**Comment by snoyberg** [comment]
Looks great now, thanks!

**Pull request merged**
