### PR TITLE
stack path: Rename --ghc-paths to --programs-path, add --compiler-path #1546

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
There's another reference to `--ghc-paths` in the guide where I'm not quite sure how to update it because I don't have a Windows system:

> On Windows, you will also need to delete `stack path --ghc-paths`

**Comment by mgsloan** [comment]
I think that comment should be updated with `--programs-path`.  I think this is the usecase for the existence of such a flag.

**Comment by sjakobi** [comment]
> I think that comment should be updated with --programs-path (and an implementation of it).

Done!

**Comment by mgsloan** [comment]
Thanks!!

**Comment by mgsloan** [comment]
FYI, I've made a few updates that bikeshed this a bit, while it's easy to change: https://github.com/commercialhaskell/stack/commit/2f7755d3a24d2b94d5f715a6cc97f7b18982e76f

**Pull request merged**
