### PR TITLE
Add initial prototype of `stack haddock --open`

### LINKED ISSUE #1396: A command `stack docs` that opens the locally installed documentation of packages?
For example, from inside the current stack project:

* `stack docs Cabal` opens
  `~/.stack/snapshots/x86_64-linux/lts-3.14/7.10.2/doc/Cabal-1.22.4.0/index.html`
* `stack --stack-yaml stack-7.8.yaml docs Cabal` opens
  `~/.stack/snapshots/x86_64-linux/lts-2.22/7.8.4/doc/Cabal-1.18.1.5/index.html`

Given that stack already installs the documentation for ghc and haddock together with the binaries, `stack docs` could also open these. There needs to be a way to distinguish between the library documentation for haddock and the user guide though.

### PR DESCRIPTION
**Pull request by yamadapc**
This is related to #1396. Definatelly not ready for merge; is this the right
direction? It'd close #1396.

### CODE REVIEW

**Comment by mgsloan** [comment]
Seems like the right implementation.  What's left till its mergeworthy?  Works for me on linux.  Maybe add a changelog entry?

**Comment by yamadapc** [comment]
I think I shouldn't use the `open-browser` package outside of Stackage, and also I'm not sure if this is the proper place to put options parsing and if we only want to open the local doc root.

Other than that it's working. I guess I'll make a PR to stackage on the end of the day? Can I do that for packages I don't own?

**Comment by yamadapc** [comment]
Just so this isn't left hanging, I'm waiting on this PR to be merged into stackage https://github.com/fpco/stackage/pull/1065

**Comment by mgsloan** [comment]
Having an extra-dep is fine!

**Comment by yamadapc** [comment]
Oh... I didn't know. Okay then, I thought the build was failing because of it... Added entry to the changelog and reworded the commit message.

**Comment by mgsloan** [comment]
Looks like the windows build is failing as well.

**Comment by yamadapc** [comment]
I believe it'll be fixed once this PR is merged to `open-browser`:

https://github.com/rightfold/open-browser/pull/14

**Comment by sjakobi** [comment]
Thanks for working on this, @yamadapc!

I just gave the new flag a try and found that it's behaviour could be even nicer/smarter:

* When I ran `stack haddock --open` in a project `.stack-work/install/x86_64-linux/lts-3.10/7.10.2/doc/index.html` was opened where I would have preferred `.stack-work/install/x86_64-linux/lts-3.10/7.10.2/doc/all/index.html`. I simply prefer `all/index.html` because I find _all_ the haddocks for all the dependencies of the project there.

* When I ran `stack haddock --open data-default-class` in the same project (of which `data-default-class` is a dependency) I got `doc/index.html` again where now I would have preferred `doc/data-default-class-0.0.1/index.html`.

* When I ran `stack haddock --open tasty` outside of any project I got an error about `~/.stack/global-project/.stack-work/install/x86_64-linux/lts-3.17/7.10.2/doc/index.html` not being found. Instead `~/.stack/snapshots/x86_64-linux/lts-3.17/7.10.2/doc/tasty-0.10.1.2/index.html`, which is available, should have been opened.

* Lastly, when I ran `stack haddock --open these` outside of any project, `these` not being part of my global snapshot lts-3.17, I again got an error about `~/.stack/global-project/.stack-work/install/x86_64-linux/lts-3.17/7.10.2/doc/index.html` not being found. Here, I would have preferred `~/.stack/global-project/.stack-work/install/x86_64-linux/lts-3.17/7.10.2/doc/these-0.6.1.0/index.html` to open.

I'm aware that most of these points are probably outside of the scope of this PR but I wanted to keep track of them somewhere.

**Comment by mgsloan** [comment]
@sjakobi 's feedback makes a lot of sense.  The meaning for `--open` that this suggests to me is one where it opens the docs for every target package.  I don't see opening multiple docs at once very useful, and potentially unexpected / spammy when a ton of tabs open.

How about it having this meaning:

* Open the package's documentation when there's only one target, even if it's a snapshot package.

* Otherwise, open `doc/all/index.html`.

**Comment by yamadapc** [comment]
Yeah, I agree. I'll update this PR with those today or tomorrow. @mgsloan thanks for the re-ping about the version bump.

**Comment by mgsloan** [comment]
Cool, looks like a new version of open-browser has been released!  So merge is just blocked on the behavior changes described by @sjakobi

**Comment by borsboom** [comment]
Are there still any changes pending for this PR, or is it ready to go now?  In any case, looks like a rebase against master is needed.

**Comment by mgsloan** [comment]
Yeah, this is pending an implementation of the behavior described by @sjakobi

**Comment by rvion** [comment]
is anyone working on this ? :)

**Comment by mgsloan** [comment]
@rvion Doesn't seem like it, feel free to have a go at this!  I'm closing the PR to avoid an appearance of PRs languishing.

**Pull request closed without merging**
