### PR TITLE
GHC color output

### PR DESCRIPTION
**Pull request by kadoban**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

Tested `stack build` with `ghc-8.2.1` resolver and got colored error output and tested in older GHC that `stack build` does not error out (would if the new flag were being passed to old GHC).

### CODE REVIEW

**Comment by snoyberg** [comment]
This is great, thanks!

One request, one question:

* Can you add a note to the changelog explaining the change?
* Does this cause the contents of the log files themselves to be unreadable? Do we need to filter out control characters when save to the log files?

**Comment by kadoban** [comment]
Anytime.

Sure, I'll add a note. I didn't initially because I wasn't sure if one was appropriate since it's more of a GHC change than a stack change, that we're then just passing through. But it makes sense to mention it, since yeah older stack versions will behave differently obviously.

Ah, that's a good question, I'll test that, the log stuff.

I'm also not sure if this covers every place that GHC output would be coming from that could use coloring. I looked around a little bit, but could definitely do some more.

**Comment by duog** [comment]
This would solve #3254

**Comment by snoyberg** [comment]
I've tested locally, and this looks good. The only (potential) downside is that the color codes are making it into the logs, e.g.

screen shot 2017-08-10 at 12 09 43 pm

I put up a little poll on Twitter to get feedback on correct behavior. There is definitely an advantage to just keeping the color codes in the log, as `cat logfile` is nice and colorful too. However, it does make it harder to use a text editor/less on the file.

**Comment by snoyberg** [comment]
I've pushed an extra commit that, when color is turned on, creates a second version of the log files with the ANSI codes stripped. Once that commit passes Travis, I'll merge this PR to master. Thanks again!

**Comment by borsboom** [comment]
> However, it does make it harder to use a text editor/less on the file.

`less -R` FTW.

**Comment by kadoban** [comment]
Thanks! Yep I couldn't find anything wrong either on my end.

**Pull request merged**
