### PR TITLE
Add documentation about the dataflow of the path command

### PR DESCRIPTION
**Pull request by NightRa**
Add documentation about the dataflow of the path command
Also, the name of the function "getMinimalEnvOverride" is misleading.
Should I change it?

### CODE REVIEW

**Comment by borsboom** [comment]
It's minimal in the sense that all none of the optional environment additions are enabled (it uses an `EnvSettings` with all fields `False`).  If you can think of a better name that still communicates that idea, feel free to change it.

**Comment by NightRa** [comment]
The path environment variable is changed though..
I'll take another look into it soon

**Comment by borsboom** [comment]
Yes, all the non-optional environment changes are still made.

**Comment by borsboom** [comment]
Didn't hear back about changing the name of `getMinimalEnvOverride`, but the rest of this is good the way it is so merging.

**Comment by NightRa** [comment]
:+1: I was just busy with other things.
If anything, I'll make another PR :)

**Pull request merged**
