### PR TITLE
Merge stable into master

### PR DESCRIPTION
**Pull request by chrisdone**
Let's kick this off. :balloon: 

I'm blocked on working on a topic branch based off of `master`, because I need to use the latest version of pantry (for writing a stack test suite entry) and `master` can't compile with it, but `stable` can.

### CODE REVIEW

**Comment by chrisdone** [comment]
I resolved the merge conflict so that all three snapshot files reference:
```yaml
- pantry-0.2.0.0
- github: snoyberg/filelock
  commit: 97e83ecc133cd60a99df8e1fa5a3c2739ad007dc
````

**Comment by snoyberg** [comment]
This is good to merge once CI goes green. Anyone with perms should feel free to do it.

**Comment by chrisdone** [comment]
Two failures on nightly:

https://dev.azure.com/commercialhaskell/stack/_build/results?buildId=2413&view=logs&jobId=22c2e4f3-60db-53c5-798d-b941136e5a82&taskId=e516a91b-8dc9-5118-e728-d1703837c34e&lineStart=6025&lineEnd=6026&colStart=1&colEnd=1
```
Running integration test 49/102: 4101-dependency-tree
Failure, dumping log


Running: /home/vsts/work/1/s/.stack-work/install/x86_64-linux/9afb0e5b524c468cc403a0d23a127cd7165def949771967acf6e96b94cdf2bf7/8.2.2/bin/stack ls dependencies tree
Cloning 4f080496d8bf153fbe26e64d1f52cf73c7db25f6 from git@github.com:snoyberg/filelock
Received ExitFailure 128 when running
Raw command: /usr/bin/git clone git@github.com:snoyberg/filelock /tmp/with-repo62626/cloned
Standard error:

Cloning into '/tmp/with-repo62626/cloned'...
Host key verification failed.
```

and 

```
Running integration test 48/102: 4095-utf8-pure-nix
Failure, dumping log


Running: /home/vsts/work/1/s/.stack-work/install/x86_64-linux/9afb0e5b524c468cc403a0d23a127cd7165def949771967acf6e96b94cdf2bf7/8.2.2/bin/stack build --nix-pure
Package name not specified, inferred "files"
error: attribute 'ghc822' missing, at (string):1:43
(use '--show-trace' to show detailed location information)
Main.hs: Exited with exit code: ExitFailure 1
```
directly above it.

Do we care about these for merging?

**Comment by snoyberg** [comment]
> `/usr/bin/git clone git@github.com:snoyberg/filelock`

That looks pretty wrong, let me look into it.

**Comment by snoyberg** [comment]
Fix pushed to `stable`, that should fix the failure.

**Comment by qrilka** [comment]
as for nix test failure - I guess we need to pin nixpkgs to some previous commit when there was GHC 8.2.2 present

**Comment by chrisdone** [comment]
Thanks!

**Pull request merged**
