### PR TITLE
WIP: Bump resolver used in release.hs

### PR DESCRIPTION
**Pull request by snoyberg**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [X] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [X] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by borsboom** [comment]
I think the integration tests might be failing due to using an LTS that requires a different GHC version than is already available.  Probably best to bump the integration tests to also use a consistent LTS.

One of these days I might just drop the `release.hs` script entirely and replace it with a simple shell script, since CI is now handling all the builds and there's no longer the need for so much complexity.  Probably not worth doing unless significant changes would be needed though.

**Comment by snoyberg** [comment]
> One of these days I might just drop the release.hs script entirely and replace it with a simple shell script,

+1 from me on that happening ultimately, but agreed, no rush

**Comment by snoyberg** [comment]
I'm in particular unable to fix up the Nix problems here. If someone else is interested in taking a crack at that, I'd really appreciate it.

**Comment by snoyberg** [comment]
I discovered the line in question here:

https://github.com/commercialhaskell/stack/blob/d1eef3febec2957e975f215689c7bb9be536184c/.github/workflows/integration-tests.yml#L58

We locked it down previously to make the test suite reproducible. But I have no idea what we should bump it to instead.

**Comment by qrilka** [comment]
Oh, I completely forgot that it was pinned, sorry, will take a look

**Comment by snoyberg** [comment]
FYI, I'm already including a workaround in this PR:

https://github.com/commercialhaskell/stack/pull/5555/commits/95d214c16674a1b80ccab9b753f73a5b0fb1c8d1

It's not as good, since it still requires two GHCs to be installed, but it does work around using the older GHC for release.hs itself.

**Comment by qrilka** [comment]
@snoyberg it looks like we can't use the last stable version 20.09 as there's no 8.10.4 there:
```
$ NIX_PATH='nixpkgs=https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz'  nix-instantiate --eval -E 'builtins.attrNames((import <nixpkgs> {}).haskell.compiler)'
unpacking 'https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz'...
[ "ghc8101" "ghc8102" "ghc822Binary" "ghc865" "ghc865Binary" "ghc882" "ghc883" "ghc884" "ghcHEAD" "ghcjs" "ghcjs86" "integer-simple" "native-bignum" ]
```
but 21.05 is almost released so I guess this should be good enough as an option
```
$ NIX_PATH='nixpkgs=https://github.com/NixOS/nixpkgs/archive/release-21.05.tar.gz'  nix-instantiate --eval -E 'builtins.attrNames((import <nixpkgs> {}).haskell.compiler)'
unpacking 'https://github.com/NixOS/nixpkgs/archive/release-21.05.tar.gz'...
[ "ghc8102Binary" "ghc8102BinaryMinimal" "ghc8104" "ghc865Binary" "ghc884" "ghc901" "ghcHEAD" "integer-simple" "native-bignum" ]
```
but there's no channel for it yet so some other way of pinning is needed

**Comment by qrilka** [comment]
@snoyberg I guess using env vars in that test could be even more explicit and we'll have the same config both in CI and locally and it looks like `NIX_PATH` is the way to go:
```
NIX_PATH='nixpkgs=https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz' stack exec -- nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
"20.09pre-git"
```

**Comment by mpilgrem** [comment]
Rather late in the day, I realised that this pull request was seeking to do part of what I am trying to do in pull request #5697 (move stack to lts-19.7/GHC 9.0.2) - but this request is for lts-8.10.4/lts-17.10. My GHC 9.0.2 pull request passes the unit tests, and the integration tests on Windows, but I am stuck with [1] the integration tests running on `macos-latest` (my current task) and [2] the integration tests that need 'alpine' or 'docker' (see https://github.com/commercialhaskell/stack/pull/5736#issuecomment-1132112610). I have not worked out how I can test CI in my fork, so I am trying to fix the CI in my pull request.

**Comment by mpilgrem** [comment]
I am going to close this pull request, as I think it has been overtaken by either #5697 (which was trying to move Stack to the current LTS, being GHC 9.0.2) or, more likely, #5763 (which is trying to move Stack to GHC 9.2.3 - the subject of the current `nightly` resolver).

**Pull request closed without merging**
