### PR TITLE
Address alias requests in #1241

### PR DESCRIPTION
**Pull request by gambogi**
Added both `runhaskell` -> `runghc` and `repl` -> `ghci`.

### CODE REVIEW

**Comment by borsboom** [comment]
Maybe add something like "(alias for 'ghci')" and "(alias for 'runghc') to the descriptions?  Otherwise, LGTM.

**Comment by gambogi** [comment]
Sure thing, I'll add that next time I'm by my computer.
-- Matt

**Comment by gambogi** [comment]
Updated!

**Comment by borsboom** [comment]
Thanks!

**Pull request merged**
