### PR TITLE
Put msys on the PATH before ghc, potential fix for #3154

### PR DESCRIPTION
**Pull request by mgsloan**
As mentioned [here](https://github.com/commercialhaskell/stack/issues/3154#issuecomment-320775528), I'm really not sure if this is a good change.  It may fix that particular problem, but it is hard to predict all the impacts of this behavior change.

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by Anrock** [comment]
@mgsloan how do i install it? I can't find info about building stack on windows and there is no artifacts in appveyour build.

**Comment by mgsloan** [comment]
@Anrock After doing a `git clone https://github.com/commercialhaskell/stack` and `git checkout msys-before-ghc-on-path-3154`, run `stack install`

**Comment by Anrock** [comment]
@mgsloan looks ok.
1. I've done `stack install` of this branch.
2. I've changed to STACK_ROOT to another dir to be sure packages are built using stack from this branch
3. I've removed XDG_DATA_DIR from Windows env vars.
Then i've tried to reproduce, using steps from original issue
`stack new foobar simple` produced error:
```
Downloaded nightly-2017-08-13 build plan.
AesonException "Error in $.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```
So i've created project with lts-9.0 resolver.
Put gi-gtk dependency in cabal file and run `stack build`. Build succeded, though i still had to define XDG_DATA_DIRS so gi-* builds could locate gir directory.

**Comment by atwupack** [comment]
@mgsloan Today I also ran into the issue with the wrong zlib dll being used during the execution of my program. Maybe a solution with less impact would be to add a new option `--no-ghc` to the `stack exec` command which prevents the path to the ghc bin from being added to the environments path.

**Comment by lwm** [comment]
> Today I also ran into the issue

@atwupack, did the existing fix on this branch solve your issue?

**Comment by atwupack** [comment]
@lwm I have tested the following:

1. Changed back the zlib1.dll to the original one in ...\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\mingw\bin. I had previously copied the dll from ...\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\bin there in order to fix the issue temporarily.
2. Ran my program with `stack exec`. This caused the error about the missing "inflateValidate" entry point.
3. Built stack based on this branch and replaced the version in ...\AppData\Roaming\Local\bin with it.
4. Ran my program again with `stack exec`. This then worked fine w/o any errors.

This fix seems to solve the issue and I did not experience any problems caused by changing the PATH order.

**Comment by mgsloan** [comment]
Sounds like this branch is not a direct fix for the issue.  I don't grok this windows stuff very well, and don't feel comfortable merging a somewhat arbitrary change to semantics.  So, closing this.

**Pull request closed without merging**
