### PR TITLE
Stack init and solver overhaul

### PR DESCRIPTION
**Pull request by harendra-kumar**
These commits are part of a series of commits to enhance the `stack init` and `solver` functionality. The goal is to be able to automatically init any project which has a working cabal file. Similarly the `stack solver` command should be able to verify and fix the configuration in an optimal manner. Also, to provide a better user experience by providing informative error messages and next steps at every failure. In other words, init should just work and be smooth and painless and always work unless the package is really broken.

See also #1529 and #1533.

The commit messages have more details about the problems and fixes. I will be adding more commits to the branch very soon. I am pushing these out for an early review. The changes are logically self contained, add incremental functionality and should not break any existing functionality.

**Please review individual commits in order and see the commit messages for an overview of each commit.**

### CODE REVIEW

**Comment by mgsloan** [comment]
Wow, this is great stuff, thanks a bunch for working on it!

Along with my commit comments, I noticed the following things that could be enhanced / fixed:

* If I do `stack init` in a directory that has a stack.yaml in an ancestor directory, I get an error.  Instead, I'd prefer that it only checked the current directory for a stack.yaml.  For example, if `~/dir/stack.yaml` exists but `~/dir/subdir/stack.yaml` doesn't:

```
mgsloan@computer:~/dir/subdir$ stack init
Stack configuration file stack.yaml exists, use 'stack solver' to fix the existing config file or '--force' to overwrite it.
```

* I also split off this issue https://github.com/commercialhaskell/stack/issues/1593

* There's an extra space towards the end of this message `- Create pivot points for the solver by specifying some extra dependencies in stack.yaml and then use 'stack solver' to figure out the rest of the  dependencies.`  Also, maybe instead of "Create pivot points for the solver by", say something like "Help the solver out by"

* When some a local package is also in a snapshot, `--solver` doesn't work.  For example, I get [this output](https://gist.github.com/mgsloan/086bfb570a592773d598) when building the latest lens repo.  I think what needs to happen is that the local packages need to get filtered out of `availablePkgs`, used to write out the `cabal.config` file.

* With an internal project, for some reason `stack init --solver` sets a flag like `time-locale-compat:-old-locale` (in the yaml, `old-locale: false`).  `time-locale-compat` does not get added to `extra-deps`, even though it needs to be present in order to work, [though this will change in the future](https://github.com/commercialhaskell/stack/issues/1265#issuecomment-168455198).  Oddly enough, the build works even if I remove the flag.  Unfortunately, I haven't yet come up with a minimal way to reproduce this.

**Comment by harendra-kumar** [comment]
1)
> If I do stack init in a directory that has a stack.yaml in an ancestor directory, I get an error. 

Can't reproduce this, code too looks fine. Maybe you really had a file in the curdir and you thought you didn't?

3) I am fixing the error message, I agree that it sounds too geeky and could be simpler.

4) Even if the local and snapshot package versions conflict, the retry should work since it relaxes the snapshot constraints to preferences. Its a good idea to fix it though.

Looking at the solver output for lens, it seems there is a conflict between the base package of the snapshot and the constraints of gloss required by lens-examples. We need a snapshot with the correct base package - in other words we need a different GHC.

The compiler compatibility check that I have put in is pretty naive as it only works for the packages we are building, it cannot check whether the dependencies of the package are compiler compatible. We will have to parse the cabal error messages for that (yucky!) - or cabal itself can provide a distinctive error.

5) I found a bug with the cabal flags parsing in the solver. I have fixed it, will push the commit soon. Maybe its related to that, try and see if the problem persists with that fix.

**Comment by mgsloan** [comment]
> Can't reproduce this, code too looks fine. Maybe you really had a file in the curdir and you thought you didn't?

Ah, I'm not sure how much the parent stack.yaml affects things (other than potentially overriding some non-project options).  However, here's a repro where if you have an invalid parent stack.yaml, things don't work: https://gist.github.com/mgsloan/2beeac1531b2ef07c651

**Comment by mgsloan** [comment]
> Looking at the solver output for lens, it seems there is a conflict between the base package of the snapshot and the constraints of gloss required by lens-examples. We need a snapshot with the correct base package - in other words we need a different GHC.

Right, that's after it falls back to using preferred versions.  When using hard constraints, it yields `rejecting: lens-4.13.1 (global constraint requires ==4.13)`.  In other words, it's writing down the lens constraint from the snapshot in the cabal config, but that mismatches with our local version.

I found this issue by running `stack init` on all the repos cloned by [diagrams-ci](https://github.com/diagrams/diagrams-ci) (I had to modify the build-universe.sh script to just clone the repos and do nothing else).

I ran into a couple miscellaneous issue while looking into this: If I delete the `version:` field in the cabal file, I get this error:

```
cabal: Error parsing config file /tmp/cabal-solver11856/cabal.config:910:
Parse of field 'constraint' failed (expected a package name followed by a
constraint, which is either a version range, 'installed', 'source' or flags):
lens==
```

> The compiler compatibility check that I have put in is pretty naive as it only works for the packages we are building, it cannot check whether the dependencies of the package are compiler compatible. We will have to parse the cabal error messages for that (yucky!) - or cabal itself can provide a distinctive error.

How about always using hard constraints for wired in packages?

> 5) I found a bug with the cabal flags parsing in the solver. I have fixed it, will push the commit soon. Maybe its related to that, try and see if the problem persists with that fix.

Cool, I do get different behavior - more flags now (`text:-integer-simple` in addition to `time-locale-compat:-old-locale`).  They don't seem to be necessary, as I can delete them.

**Comment by harendra-kumar** [comment]
> here's a repro where if you have an invalid parent stack.yaml

This warrants a separate issue. Perhaps we should avoid loading project config for init. Currently it uses `withConfigAndLock` which parses existing stack.yaml. We don't need to parse it for init, we only need to check the existence of it.

**Comment by harendra-kumar** [comment]
> If I delete the version: field in the cabal file, I get this error:

I did not realize that version could remain empty for source packages. Thanks for catching this! I uploaded the fix. The fix assumes that if the package is in the Hackage index as well cabal will do the right thing and pick up the source version instead of the index version.

**Comment by harendra-kumar** [comment]
> How about always using hard constraints for wired in packages?

Cabal anyway does that. It puts the wired-in packages in global constraints before solving.

**Comment by harendra-kumar** [comment]
I am sorry, I never compiled with GHC 7.8.4. I have a fix for the CI build failure, should I rebase and squash with the last commit or just push another commit? Let me know if there is anything else to be taken care of as well. Many thanks for spending time on reviewing, testing and providing useful feedback.

**Comment by harendra-kumar** [comment]
I found a couple of issues with flags. 

When solver returns flag changes for packages which are in snapshot, we update the flags in stack.yaml but we do not put those packages in extra dependencies. When we run `stack build` it complains about it.

We are not comparing the snapshot package flags (we compare only the version) when determining extra dependencies. If the snapshot flags are different than those the solver arrived at then we need to put those packages in extra dependencies. Otherwise the plan will not build because the status of flags can change dependencies.

This can be tested on stack itself. If we run `stack init --resolver lts-2.22 --solver` for stack itself the resulting plan is broken due to this problem. I will fix it tomorrow.

**Comment by mgsloan** [comment]
> This warrants a separate issue. Perhaps we should avoid loading project config for init. Currently it uses withConfigAndLock which parses existing stack.yaml. We don't need to parse it for init, we only need to check the existence of it.

I've opened https://github.com/commercialhaskell/stack/issues/1604 . Yeah, I think we should be able to avoid using `withConfigAndLock`

> I am sorry, I never compiled with GHC 7.8.4. I have a fix for the CI build failure, should I rebase and squash with the last commit or just push another commit? Let me know if there is anything else to be taken care of as well. Many thanks for spending time on reviewing, testing and providing useful feedback.

No problem, that's what CI is for!  Pushing another commit is fine, we have lots of "Fix build on GHC 7.8" commits..

Many thanks for spending time on implementing this!  The next steps you've described sound good.

**Comment by harendra-kumar** [comment]
It now gives a workable plan for stack itself using lts-2.22 and solver. Can you try it again now and see if you encounter any issues?

**Comment by harendra-kumar** [comment]
We will have to update the documentation as well. I guess I can do that via a separate PR?

**Comment by mgsloan** [comment]
Looks good!  Feel free to do documentation in this PR, or a different one.  I suppose I'd prefer including it with this one, but it's no big deal.

I'm still running into the issue where there are hard constraints which disagree with local package versions.  Could you please try this repro?

```
git clone https://github.com/mgsloan/diagrams-ci
cd diagrams-ci
git checkout stack-repro-for-1583
./build-universe.sh    # Doesn't actuall build, due to my one commit on the repo
cd build-tmp
stack init --solver
```

**Comment by mgsloan** [comment]
Also with that repro, I get all the local packages having entries in `flags`, if I `stack init --solver --force`:

```
flags:
  diagrams-contrib: {}
  diagrams-lib: {}
  ...
```

It'd be best to leave these out!

**Comment by harendra-kumar** [comment]
I will try the diagrams-ci test. For documentation, I was only worried about merge conflicts if this PR stays longer. I will assess how many changes are needed and then we can decide to postpone or not.

I thought I filtered out the empty flags but might have missed something, will check.

**Comment by harendra-kumar** [comment]
The empty flags were getting through only in case of `--force` I fixed that. Another nice-to-have is to not write the flags if they are unchanged from defaults. Currently we are writing the default values of manual flags.

The solver errors are due to conflicting requirements of source packages in the diagrams suite. Here is the output I am getting:

```
cabal: Could not resolve dependencies:
trying: active-0.2.0.8 (user goal)
trying: diagrams-input-0.1 (user goal)
next goal: diagrams-lib (user goal)
rejecting: diagrams-lib-1.3.0.8, 1.3.0.7, 1.3.0.6, 1.3.0.5, 1.3.0.4, 1.3.0.3,
1.3.0.2, 1.3.0.1 (global constraint requires ==1.3)
trying: diagrams-lib-1.3
next goal: linear (dependency of active-0.2.0.8)
rejecting: linear-1.19.1.3, 1.20.3, 1.20.2, 1.20.1, 1.20, 1.19.1.2, 1.19.1.1,
1.19.1, 1.19 (conflict: diagrams-input => linear>=1.11.3 && <1.19)
rejecting: linear-1.18.3, 1.18.1.1, 1.18.1, 1.18.0.1, 1.18, 1.17.1, 1.17,
1.16.4, 1.16.2, 1.16.1, 1.16, 1.15.5, 1.15.4, 1.15.3, 1.15.2, 1.15.1,
1.15.0.1, 1.15, 1.14.0.1, 1.14 (conflict: diagrams-lib => linear>=1.20.1 &&
<1.21)
rejecting: linear-1.13, 1.12.1, 1.11.3, 1.11.2, 1.11.1, 1.11, 1.10.1.2,
1.10.1.1, 1.10.1, 1.10, 1.9.1, 1.9.0.1, 1.9, 1.8.1, 1.8, 1.7, 1.6, 1.4,
1.3.1.1, 1.3.1, 1.3, 1.2, 1.1.4, 1.1.2, 1.1.1, 1.0.1, 0.9.2, 0.9.1, 0.9, 0.8,
0.7, 0.6.1, 0.6, 0.5, 0.4.2.2, 0.4.2.1, 0.4.1, 0.2.0.2, 0.2 (conflict: active
=> linear>=1.14 && <1.21)
Dependency tree exhaustively searched.
```

Here source packages active, diagrams-input and diagrams-lib have a conflict on linear. Among themselves the dependencies are `diagrams-input->diagrams-lib->active`. So we can perhaps remove diagrams-input and anything that depends on that from our source packages and it should work. It indeed worked when I removed it.

So maybe a future enhancement can be to automatically suggest which user packages can be removed to get a working plan.

**Comment by harendra-kumar** [comment]
A very clean stack.yaml is generated now. I have added logic to remove flags with default values as well. 

I might push one more commit to report compiler incompatibility errors for each individual source package rather than once for the whole set. That way the user can easily identify exactly which package has problems.

**Comment by mgsloan** [comment]
This is a great set of changes, thanks for all your excellent work!

I [fixed a warning](https://github.com/commercialhaskell/stack/commit/f050d497f2f3e87e2ad517710006649564ebb604) that cropped up due to [now reporting more warnings](https://github.com/commercialhaskell/stack/commit/0b1b9c21fe1dc1f58f036867fcb0774a98193bc7).

**Comment by mgsloan** [comment]
RE the diagrams-haddock thing, you're probably right, I was just getting confused by the wording of cabal-install's output.

**Comment by harendra-kumar** [comment]
Great. Thanks! I will try to fix the user guide in the next couple of days.

**Comment by borsboom** [comment]
Looks like there's a syntax error in the haddocks:
```
src/Stack/Solver.hs:306:25:
    parse error on input ‘-- ^ src package constraints’
     (src/Stack/Types/Internal.hs:56)
    HasSupportsUnicode (src/Stack/Types/Internal.hs:59)
     (src/Stack/Types/Internal.hs:62)
    Sticky (src/Stack/Types/Internal.hs:65)
    HasSticky (src/Stack/Types/Internal.hs:69)
     (src/Stack/Types/Internal.hs:72)
```

**Comment by harendra-kumar** [comment]
Can we include haddock in CI?

**Comment by mgsloan** [comment]
Sure! Added in https://github.com/commercialhaskell/stack/commit/92da37a463a444dcdc94cb64f9bac14c74cb7e8a

**Comment by mgsloan** [comment]
Unfortunately, it doesn't work: https://github.com/commercialhaskell/stack/issues/1623

**Comment by harendra-kumar** [comment]
I see you already fixed the haddock issues. Thanks!

**Pull request merged**
