### PR TITLE
Travis: download stack for cabal builds

### LINKED ISSUE #2390: Travis build uses stack but doesn't download it on builds
The original build script build doesn't find `stack` when CI-ing my fork:
https://travis-ci.org/Blaisorblade/stack/jobs/145802415#L213-L217

That leads to a build failure because cabal uses the cabal file in master and selects the wrong versions of dependencies—in particular, it picks versions of `binary` and `Cabal` that both declare the same typeclass instance.

Working hypothesis: .travis.yml use stack in cabal builds, but `.travis-setup.sh` doesn't download it for cabal builds.

I conjecture that might work on your fork because there's stack in the build caches—since they cache the result of building stack.
But at some point this might lead to unexpected build configurations and hard-to-debug bugs.

My action plan:
1. I test my hypothesis by trying a fix to the build scripts
2. Ideally, somebody (I, if I manage) change the build to avoid storing the final binary.
3. If that works, you might want to verify my conjecture by clearing the Travis cache once and observing the build failure—or not, it's of course your call.

### PR DESCRIPTION
**Pull request by Blaisorblade**
Fix #2390:
- download stack before using it;
- error out if the uses of stack fails;
- pass enough options to stack to make it work without requiring `stack setup` (specifically, pick correct stack file and GHC version).

This still does not ensure a successful build from scratch on GHC-7.8.4, but it still fixes a clear bug.

### CODE REVIEW

**Comment by mgsloan** [comment]
Thanks!  Looks like there's a CI error.

**Comment by Blaisorblade** [comment]
@mgsloan I'm afraid most of the context is in #2390, hence I'm answering there—sorry this is awkward.

**Comment by sjakobi** [comment]
These changes make a lot of sense regardless of whether https://github.com/commercialhaskell/stack/pull/2273 happens or not.

Please just rebase this if necessary once #2273 has been decided.

The `lifted-base` bound has been fixed on `master`.

**Comment by borsboom** [comment]
These changes look good to me.  Go ahead and merge it after any necessary rebases and CI error fixes.

**Comment by mgsloan** [comment]
LGTM!

**Pull request merged**
