### PR TITLE
Start implementing #3006

### PR DESCRIPTION
**Pull request by alexeyzab**
* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

This changes `GitSHA1` from using a `ByteString` to a `StaticSize 40 ByteString`. Other edits make sure the code compiles and the tests pass.

It was not possible to derive a `Hashable` instance after the change, so I've implemented one by hand.

I have commented out the implementation of `peek` and `poke` for `GitSHA1`'s `Store` instance as I am not sure if those are needed or not.

If these changes are satisfactory, I'll start working on the `Stack.Types.PackageIndex.PackageDownload.pdSHA256`'s instances as well.

### CODE REVIEW

**Comment by alexeyzab** [comment]
I went ahead and made the changes to `Stack.Types.PackageIndex.PackageDownload.pdSHA256`. If this needs more work, let me know.

**Comment by mgsloan** [comment]
Hey!  Sorry for the delay on feedback.  Looks good to me!  One thing is that the version tags, like (`storeVersionConfig "pkg-v2" ...)` should have its name updated (so, `pkg-v2`), since this will actually cause a difference in serialization.  With the StaticSize version, the size won't get stored in the file at all.

**Comment by alexeyzab** [comment]
@mgsloan To clarify, should it be changed `pkg-v3`? I've adjusted the hash, but didn't touch this part.

On a separate note, should I remove the commented out definitions of [`poke` and `peek` for `GitSHA1`](https://github.com/commercialhaskell/stack/pull/3120/files#diff-c915b6fa64991afe9ae33739482900ffR470)? I put them in just in case they might be necessary here.

Thanks!

**Comment by snoyberg** [comment]
I totally broke this PR with extensible-snapshots, which switched from GitSHA1 to a SHA256. I'm going to this it up and open a new PR, I'll add a comment when that's done.

**Comment by snoyberg** [comment]
PR #3260 is now open. When it's merged, it will merge this PR too.

**Comment by snoyberg** [comment]
Continuing the discussion from the other PR: here's a really hacky implementation of the `Word64` idea I mentioned: https://github.com/snoyberg/static-bytes

**Comment by alexeyzab** [comment]
That's pretty interesting. If we were to use that library, we'd change `StaticSHA256` to something like 

```haskell
data StaticSHA256 = StaticSHA256 !Bytes32
```

Is that right? And then get rid of the `StaticSize` altogether.

**Comment by snoyberg** [comment]
Yes, though I'd prefer a `newtype` wrapper in this case. But I'd recommend considering that separate from this PR to avoid slowing it down.

**Comment by alexeyzab** [comment]
Makes sense. In that case it seems all that's left here is to edit the `ChangeLog.md`, I'll do that now.

**Comment by alexeyzab** [comment]
@snoyberg Thanks for walking me through what needed to be done here!

**Comment by snoyberg** [comment]
No problem, thank you! It looks like the PR is showing all of my changes on extensible-snapshots as differences, which is a bit annoying... anyway, I think this is good to go. @mgsloan, did you have any objections to merge?

**Comment by alexeyzab** [comment]
I wonder if that's because I merged something the wrong way.

I believe these are the relevant commits for this PR:
https://github.com/commercialhaskell/stack/pull/3120/commits/14533459f7cef7e9aa43a7e30f87870383a731ed
https://github.com/commercialhaskell/stack/pull/3260/commits/8c87d12b963956aeeb8b9f8802cc9eeefcf0212b
https://github.com/commercialhaskell/stack/pull/3260/commits/696d9b4e61617c59e017e5cc922c79bef08df0b1
https://github.com/commercialhaskell/stack/pull/3120/commits/54ff6326c40718395da8bd0deb72d68bdee7eac9

Where the last two overwrite some parts of the first two.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
